### ISSUE TITLE
Timestamp only when dependencies change

### ISSUE THREAD

**Issue by taavo** [pivotal/LicenseFinder#114]
In certain projects it's necessary to check in doc/dependencies.*, and we want developers running license_finder frequently. We'd prefer if the timestamps in dependencies.html/md/etc only changed when the dependencies changed, or at least if there were an option to enable this behavior.

Also, you may want to consider using an ISO timestamp. Otherwise the timestamp will thrash depending on the timezone setting of the machine on which license_finder runs.

Example diff:
```diff
diff --git a/doc/dependencies.html b/doc/dependencies.html
index cc48bab..f4207c9 100644
--- a/doc/dependencies.html
+++ b/doc/dependencies.html
@@ -29,7 +29,7 @@
       <div class="span5">
         <h2>Dependencies</h2>

-        <p>As of September 22, 2014  6:28pm</p>
+        <p>As of September 22, 2014  6:57pm</p>

         <h4>12 total</h4>

diff --git a/doc/dependencies.md b/doc/dependencies.md
index 85f6e0a..a44df6d 100644
--- a/doc/dependencies.md
+++ b/doc/dependencies.md
@@ -1,6 +1,6 @@
 # Node Gemfire

-As of September 22, 2014  6:28pm. 12 total
+As of September 22, 2014  6:57pm. 12 total

 ## Summary
 * 10 MIT
```

cc @nertzy

**Comment by mainej** [comment]
Closing this with the [release of 2.0](https://groups.google.com/forum/#!topic/license-finder/rPfVHOiLI-U).  Fixing this kind of problem was a major motivation for the 2.0 work, so thanks for contributing to this discussion.
