### ISSUE TITLE
option to scan without updating `docs`

### ISSUE THREAD

**Issue by LukeWinikates** [pivotal/LicenseFinder#117]
My use case is running `license_finder` from a rake task. I want to run `license_finder` as part of my test suite before pushing commits to master, but don't want the default rake task to update `license_finder`'s artifacts in the `doc` directory.

**Comment by mainej** [comment]
Closing this with the [release of 2.0](https://groups.google.com/forum/#!topic/license-finder/rPfVHOiLI-U).  Fixing this kind of problem was a major motivation for the 2.0 work, so thanks for contributing to this discussion.
