### ISSUE TITLE
LF pulling up python bridge framework dependencies 

### ISSUE THREAD

**Issue by pivotal-tortuga** [pivotal/LicenseFinder#119]
https://github.com/coretech/tortuga-gw

Pulls up depdencies for the libraries below, problem is none are used in our app:  
pyobjc-core, 2.3.2a0, other
pyobjc-framework-AddressBook, 2.3.2a0, other
pyobjc-framework-AppleScriptKit, 2.3.2a0, other
pyobjc-framework-AppleScriptObjC, 2.3.2a0, other
pyobjc-framework-Automator, 2.3.2a0, other
pyobjc-framework-CFNetwork, 2.3.2a0, other
pyobjc-framework-Cocoa, 2.3.2a0, other
pyobjc-framework-Collaboration, 2.3.2a0, other
pyobjc-framework-CoreData, 2.3.2a0, other
pyobjc-framework-CoreLocation, 2.3.2a0, other
pyobjc-framework-CoreText, 2.3.2a0, other
pyobjc-framework-DictionaryServices, 2.3.2a0, other
pyobjc-framework-ExceptionHandling, 2.3.2a0, other
pyobjc-framework-FSEvents, 2.3.2a0, other
pyobjc-framework-InputMethodKit, 2.3.2a0, other
pyobjc-framework-InstallerPlugins, 2.3.2a0, other
pyobjc-framework-InstantMessage, 2.3.2a0, other
pyobjc-framework-InterfaceBuilderKit, 2.3.2a0, other
pyobjc-framework-LatentSemanticMapping, 2.3.2a0, other
pyobjc-framework-LaunchServices, 2.3.2a0, other
pyobjc-framework-Message, 2.3.2a0, other
pyobjc-framework-OpenDirectory, 2.3.2a0, other
pyobjc-framework-PreferencePanes, 2.3.2a0, other
pyobjc-framework-PubSub, 2.3.2a0, other
pyobjc-framework-QTKit, 2.3.2a0, other
pyobjc-framework-Quartz, 2.3.2a0, other
pyobjc-framework-ScreenSaver, 2.3.2a0, other
pyobjc-framework-ScriptingBridge, 2.3.2a0, other
pyobjc-framework-SearchKit, 2.3.2a0, other
pyobjc-framework-ServiceManagement, 2.3.2a0, other
pyobjc-framework-SyncServices, 2.3.2a0, other
pyobjc-framework-SystemConfiguration, 2.3.2a0, other
pyobjc-framework-WebKit, 2.3.2a0, other

**Comment by mainej** [comment]
Here's a naive narrative of what's going on.  (This is probably obvious, but I'm not a Python person.)

* A virtualenv is a collection of installed packages.  While a virtualenv is `active`, any packages installed with pip will be put in that virtualenv.
* A `requirements.txt` file contains a list of packages, and `pip install -r requirements.txt` makes sure all those packages are installed (in the active virtualenv, if there is one).
* If `pip install -r` is called for two different files, the packages from both files will be installed, possibly into the same virtualenv.
* At runtime, `requirements.txt` is irrelevant.  Python will use the installed packages, regardless of how they were installed.  No error will be raised if a package is installed but not present in `requirements.txt`.  This is quite different from how `bundler` uses a `Gemfile` to restrict which packages can be used.
* `license_finder` asks `pip` for a list of *installed* packages. Again, the installed packages may include packages from many projects.
  * This may explain why creating a new (empty) virtualenv before running `license_finder` gets the desired behavior, though I'd expect you'd have to create *and* activate it.
* So, `license_finder` doesn't answer "what packages _will_ this project use?" but rather "what packages _could_ this project use?"
* To answer the first question, as @flavorjones suggested, we'd have to:
  * trust that `requirements.txt` lists all the dependencies
  * parse `requirements.txt` similarly to how `pip install -r` does it (see [here](https://pip.pypa.io/en/latest/reference/pip_install.html#requirement-specifiers))
  * do the same recursion that pip (and/or setuptools) does to find dependencies' dependencies.
