### ISSUE TITLE
Does not exit nonzero when dependencies need approval

### ISSUE THREAD

**Issue by jamie** [pivotal/LicenseFinder#134]
Trying to set this up for CI as mentioned https://github.com/pivotal/LicenseFinder#continuous-integration, 2.0.0.rc2 seems to be exiting with a 0 status code even with output:

```
Dependencies that need approval:
systemu, 2.6.4, "same as ruby's"
```

**Comment by mainej** [comment]
Can you submit a Gemfile, license_finder.yml and dependency_decisions.yml file which demonstrate this?  Please be sure to redact sensitive information.

**Comment by mainej** [comment]
The output of `license_finder --debug` would also be useful, again with sensitive information redacted.

**Comment by jamie** [comment]
I apologize.

Went to repro and minimal Gemfile worked as advertised, copied over my work app's Gemfile and it also worked. Turns out that the shell alias I usually use to avoid `bundle exec` everywhere is eating the exit status.
