### ISSUE TITLE
Could not find command "report".

### ISSUE THREAD

**Issue by AndydeCleyre** [pivotal/LicenseFinder#137]
$ gem list license_finder 

    *** LOCAL GEMS ***

    license_finder (1.2)

    $ license_finder --help report
    Could not find command "report".

    $ license_finder report --format html
    Could not find command "report".

What happened to the report generation?

**Comment by mainej** [comment]
The `report` command is new as of v2.0 (which will be in pre-release for a few more weeks.)  You have two options:
* Upgrade to 2.0.0.rc2
  * Use [this gem](https://github.com/mainej/license_finder_upgrade) to assist with the upgrade,
  * but install `license_finder` with `gem install license_finder --pre`
* Refer to [the v1.2 docs](https://github.com/pivotal/LicenseFinder/tree/v1.2) for the commands supported in that release.

**Comment by mainej** [comment]
I just released v2.0 to rubygems.org, so you no longer need the `--pre` tag when installing.
