### ISSUE TITLE
Gradle dependency license url not extracted

### ISSUE THREAD

**Issue by slimjim2234** [pivotal/LicenseFinder#147]
Using the gradle plugin with license_finder, the name, version, and license columns work correctly.  However, the homepage is never populated.

example run:
license_finder report --format=csv --columns=name version licenses homepage

Using license-gradle-plugin v0.11.0 with license_finder 2.0.3

**Comment by mainej** [comment]
If you know of a way to extract homepage from gradle's output, I'd happily accept a patch.  Or just point me to the documentation and I'll see if we can get to it.

**Comment by slimjim2234** [comment]
I am not too sure how LicenseFinder currently acquired the information, but I know that it requires the following project https://github.com/hierynomus/license-gradle-plugin.
This project produces an xml formatted file with the url imbedded in the license tag.

I have created a quick and dirty bash script to parse this and get this url which mainly uses xmlstartlet.
The following command will extract the license url(s) along with the name of the gradle dependency in a csv format:
`/usr/local/bin/xmlstarlet sel -t -m //dependency -v file  -m license -v "concat(', ', @url)" -b -n dependency-license.xml`

I can assist in making the modifications but I am no ruby expert.

**Comment by mainej** [comment]
Hmm, that's the license url, but homepage is supposed to be the project's
repo or docs. We have links to most licenses via another code path. Would
it help if we made those urls available in the csv?

**Comment by slimjim2234** [comment]
ah! my apologies, i meant the license url.  Not the project homepage.
yes, the links would be extremely helpful if they were made available in csv format.

**Comment by mainej** [comment]
@slimjim2234 I played with including the license urls in the CSV, but I'm not happy with how it's working.  Packages with many licenses have may license urls, and nesting CSVs inside other CSVs doesn't seem like a good idea.  We already have a list of license names in the CSV, which in retrospect probably wasn't a good idea.  I can think of a few other approaches:

1. (preferred) It's pretty easy to write [a ruby script](https://gist.github.com/mainej/48ac616844505d50f510) which extracts data from license_finder.  You could use that data to output custom CSVs or JSON or just integrate with other ruby code.
2. If you want to see a list of all licenses, you can look at `LicenseFinder::License.all`.  It's just a list of licenses which license_finder recognizes, and doesn't show you which ones are associated with which packages.
3. We could write a command line tool `license_finder licenses known`, which outputs some of the data you could get from `LicenseFinder::License.all`.
4. We could write a command line tool `license_finder --format json` which outputs JSON, including packages, their licenses, and the license's urls.  However, we've found that our users each want slightly different report output, so we're trying to avoid writing reports and recommending that people write custom scripts instead.

**Comment by mainej** [comment]
Closing this, assuming that the custom ruby script is sufficient.
