### ISSUE TITLE
problem encountered using license_finder with cocoapods 0.37.0

### ISSUE THREAD

**Issue by akitchen** [pivotal/LicenseFinder#151]
Hello,

We tried running ```license_finder``` against our codebase, which is using cocoapods 0.37.0 and were met with the following:
```
................................................................................................................../Users/pivotal/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/license_finder-2.0.4/lib/license_finder/package_managers/cocoa_pods.rb:51:in `read_plist': undefined method `expand_path' for nil:NilClass (NoMethodError)
	from /Users/pivotal/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/license_finder-2.0.4/lib/license_finder/package_managers/cocoa_pods.rb:34:in `license_texts'
	from /Users/pivotal/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/license_finder-2.0.4/lib/license_finder/package_managers/cocoa_pods.rb:16:in `block in current_packages'
	from /Users/pivotal/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/license_finder-2.0.4/lib/license_finder/package_managers/cocoa_pods.rb:8:in `map'
	from /Users/pivotal/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/license_finder-2.0.4/lib/license_finder/package_managers/cocoa_pods.rb:8:in `current_packages'
	from /Users/pivotal/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/license_finder-2.0.4/lib/license_finder/package_manager.rb:37:in `current_packages_with_relations'
	from /Users/pivotal/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/license_finder-2.0.4/lib/license_finder/package_manager.rb:23:in `each'
	from /Users/pivotal/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/license_finder-2.0.4/lib/license_finder/package_manager.rb:23:in `flat_map'
	from /Users/pivotal/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/license_finder-2.0.4/lib/license_finder/package_manager.rb:23:in `current_packages'
	from /Users/pivotal/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/license_finder-2.0.4/lib/license_finder/core.rb:60:in `current_packages'
	from /Users/pivotal/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/license_finder-2.0.4/lib/license_finder/core.rb:55:in `decision_applier'
	from /Users/pivotal/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/license_finder-2.0.4/lib/license_finder/cli/main.rb:26:in `action_items'
```
Any help or pointers appreciated.  are we doing something wrong?

**Comment by flavorjones** [comment]
Hi Andrew,

Without more information, I can't reproduce it and thus can't accurately diagnose.

That said: do you have a file named `Pods-acknowledgements.plist` somewhere in your project tree? If so, where is it? (LF assumes it's in either `Pods` or `Pods/Target Support Files/Pods`, which correspond to the behavior of various versions of cocoapods (see #118 for some historical context).

**Comment by flavorjones** [comment]
Worth noting that the test suite passes on cococapods 0.37.1 (I just checked). So, more info on the location of your acknowledgements file would be helpful. Thanks.

**Comment by akitchen** [comment]
OK, maybe we have made a mistake in setup.  we will look into it further and follow up later.

thanks Mike.

**Comment by akitchen** [comment]
Our codebase didn't have a ```Pods-acknowledgements.plist``` anywhere.  I assume that is a file generated by cocoapods?

Our project ended up migrating away from cocoapods since it was adding warnings to our build process which could not be fixed by us or suppressed, making it so that we were not able to treat warnings as errors.  And we prefer to treat warnings as errors.

I won't be able to follow up much more on this issue in the context of this project, so feel free to close if no one else has been experiencing this problem.

**Comment by mainej** [comment]
Haven't heard further reports of problems, so closing.  Please re-open if it crops up again.
