### ISSUE TITLE
Config file support for nonstandard directory structures

### ISSUE THREAD

**Issue by LukeWinikates** [pivotal/LicenseFinder#153]
I've got a repo with roughly this layout:

```
+-- RadProject
|   +-- AwesomeAPI
|   +-- FancyFrontend
```

I've got one license whitelist, but I've got 3 package managers-- one for the API, plus `npm` and `bower` for the frontend. I'd like to manage all the approvals in one place and have just one home directory for `LicenseFinder`. `LicenseFinder` expects to be run from the directory containing whatever dependency files it's scanning, so has a hard time with this directory structure.

I'd like to add path options to license_finder.yml so that we could say, e.g:
```yml
bower: FancyFrontend/bower.json
```

I've never wanted this before, but it feels reasonable for the project I'm working on. It's admittedly configuration rather than convention.

I'm interested in alternative suggestions or ideas, or encouragement to submit a PR.

**Comment by mainej** [comment]
Haven't tested this, but try it out...

Upgrade to the latest license_finder (2.0.4 at the moment), then:

```
cd RadProject
license_finder --decisions-file=path/to/shared/dependency_decisions.yml --project-path= AwesomeAPI
license_finder --decisions-file=path/to/shared/dependency_decisions.yml --project-path= FancyFrontend
```

I *think* that license_finder will share your whitelist and approvals across both projects.  You'll have to be sure to specify that same shared `dependency_decisions.yml` file whenever you interact with license_finder.

**Comment by LukeWinikates** [comment]
Finally was able to try this, and it works for our project. Thanks @mainej !
