### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by akitchen** [pivotal/LicenseFinder#154]
It would be lovely if licensefinder could support Carthage, a lighterweight dependency manager vs. CocoaPods

https://github.com/Carthage/Carthage

Dependencies are listed in a Cartfile in the project, usually with URLs to github or other hosted repos.

**Comment by mainej** [comment]
If anyone wants to take this on, the [contributing guidelines](https://github.com/pivotal/LicenseFinder/blob/master/CONTRIBUTING.md) reference a [series of changes](https://github.com/pivotal/LicenseFinder/compare/v2.0.0...v2.0.1) which added Rebar, the erlang package manager.  That change list is a good reference for everything that needs to be updated when adding a new package manager.

**Comment by kdykeman** [comment]
See #283
