### ISSUE TITLE
Incomplete refactoring in GoPackage?

### ISSUE THREAD

**Issue by mainej** [pivotal/LicenseFinder#157]
`GoWorkspace#current_packages` references `workspace_root`, but that's never used.  Maybe it should be `install_prefix`?

It's hard to tell what was going on with the refactoring that shared `GoPackage` between `GoWorkspace` and `GoDep`.  `GoWorkspace` might be easier to read and reason about if it were refactored to prefer Pathname over string manipulation.  For example, it looks like `GoWorkspace` tries to implement `Pathname#relative_path_from`.  `GoPackage` has similar problems.

**Comment by erd** [comment]
We did some refactoring in 374865752478c6886f11001db06f12f022ad1ad7 to try and clean up the division of labor between `GoWorkspace`, `GoDep` and `GoPackage`. Thanks for the tip about `Pathname#relative_path_from` - I didn't know about that one.
