### ISSUE TITLE
Recent breakage of windows support

### ISSUE THREAD

**Issue by LukeWinikates** [pivotal/LicenseFinder#158]
NPM and Bower support worked on windows until fairly recently. I think that the issue is the recent addition of `cd #{project_path};` to the NPM command and elsewhere. Windows' command line doesn't support `;`.

Could LicenseFinder use `&&` instead?

(+ @erd , whose name I recognize from the [relevant commit](https://github.com/pivotal/LicenseFinder/commit/97974291d741309d26298c6a2b0c3efc6d11b938))

**Comment by erd** [comment]
Thanks for pointing this out! We'll try and take a look at it this week.

**Comment by erd** [comment]
@LukeWinikates Would you mind taking the above PR for a spin and let me know if it fixes your issues on Windows? If so, I'll merge it. Thanks!

**Comment by LukeWinikates** [comment]
Let's close this once @erd 's PR is merged
