### ISSUE TITLE
Support for a Multi-Project Gradle project

### ISSUE THREAD

**Issue by nkoterba** [pivotal/LicenseFinder#162]
So this is more a question since the documentation seems sparse in this area.

We have a Multi-Project Gradle project with various `build.gradle` files nested throughout a directory structure.  

Running `license_finder` at the top-level `build.gradle` file only lists dependencies for that top-level project.  

Thus, we have a script that runs `license_finder` in all the directories where we have a `build.gradle` or `package.json` or `bower.json` file.

We would, however, like a master 'dependency' database.  

Is the way to accomplish this by creating a `config/license_finder.yml` in each directory where we want to run `license_finder` and then have it point to a master `doc/dependency_decisions.yml` we have at the top of our directory hierarchy?

Or should we pass `--decisions_file` parameters each time we run `license_finder` in a directory and have it always point to the same file at the top of our directory hierarchy?

Also, has there been any talk about supporting multi-project gradle setups?  Meaning I could run `license_finder` at the top-level `build.gradle` file and it would run through all the subprojects it knows about and report licenses for each sub-project?

**Comment by mainej** [comment]
I'm not sure if it's been released to RubyGems, and I've never used the feature personally, but it looks like [support for nested projects](https://github.com/pivotal/LicenseFinder/blob/master/lib/license_finder/cli/main.rb#L62-L63) was recently added to LicenseFinder.  The `report` command can automatically detect nested projects with `--recursive` or if that fails, you can manually specify the nested projects with `--subprojects`.

Give those a shot, but if you can't get them working, see another solution in #153.  You were on the same track... in the root directory create a `config/license_finder.yml` that points to a shared `--decisions_file`, then run license_finder multiple times with different values for `--project_path`.

**Comment by nkoterba** [comment]
@mainej When you say "not sure if it's been released to RubyGems" do you mean that I need to install from the Github source vs `gem install license_finder`?

I'm running version 2.0.4 installed via gem, and when I try `license_finder report --recursive`, I get:
```javascript
nk-mbp:Code a$ license_finder report --recursive
ERROR: "license_finder report" was called with arguments ["--recursive"]
Usage: "license_finder report"
```

I also don't think `--subprojects` is implemented in the RubyGems version either.

So until those become "officially" available, I may just go with your latter suggestion.  Thanks!

**Comment by mainej** [comment]
@nkoterba Yep, looks like you'd have to install from GitHub to get those features.

**Comment by mainej** [comment]
Can we close this issue?  Sounds like it's working, per #165?

**Comment by nkoterba** [comment]
Yep. Close away...I've been using teh GitHub version and will continue to do so until v2.0.5 is pushed to RubyGems.

**Comment by mainej** [comment]
OK, glad it's working.  I hope we get 2.0.5 out for you soon.
