### ISSUE TITLE
Issue Adding 'Eclipse Public License - v 1.0, GNU Lesser General Public License' to Whitelist

### ISSUE THREAD

**Issue by nkoterba** [pivotal/LicenseFinder#163]
Several of my dependencies use the following license (as reported by License_finder):

`Eclipse Public License - v 1.0, GNU Lesser General Public License`

Unfortunately, I've tried adding this license multiple times to my whitelist and although it appears in my `dependency_decisions.yml` file, 

```javascript
- - :whitelist
  - Eclipse Public License - v 1.0, GNU Lesser General Public License
  - :who: a
    :why: Eclipse Public License v1.0 license is approved for SNAP usage.
    :when: 2015-07-29 19:41:09.690922000 Z
```

I still get the following when I run `license_finder`:

```javascript
nk-mbp:Code a$ license_finder
..............Dependencies that need approval:
logback-core, 1.1.2, "Eclipse Public License - v 1.0, GNU Lesser General Public License"
logback-classic, 1.1.2, "Eclipse Public License - v 1.0, GNU Lesser General Public License"
```

Other dependencies that use for example, `MIT` or `Apache 2.0` are correctly being identified on the whitelist.

Is there a possible issue with the Eclipse Public License text string?  Perhaps the `,` is confusing the library?  

Here's a simple `build.gradle` file that should cause the issue:
```java
plugins {
    id "com.github.hierynomus.license" version "0.11.0"
}

repositories {
        mavenCentral()
}

apply plugin: 'java'

dependencies {
        runtime(
                "ch.qos.logback:logback-classic:1.1.2"
)
}
```

Run `license_finder` in that directory.  Notice how it reports 3 dependencies:
```javascript
.............Dependencies that need approval:
logback-core, 1.1.2, "Eclipse Public License - v 1.0, GNU Lesser General Public License"
logback-classic, 1.1.2, "Eclipse Public License - v 1.0, GNU Lesser General Public License"
slf4j-api, 1.7.6, MIT
```

We add `MIT` to whitelist and re-run:
```javascript
.............Dependencies that need approval:
logback-core, 1.1.2, "Eclipse Public License - v 1.0, GNU Lesser General Public License"
logback-classic, 1.1.2, "Eclipse Public License - v 1.0, GNU Lesser General Public License"
```

We add `EPL` to the whitelist:

`license_finder whitelist add "Eclipse Public License - v 1.0, GNU Lesser General Public License"`

and re-run:
```javascript
.............Dependencies that need approval:
logback-core, 1.1.2, "Eclipse Public License - v 1.0, GNU Lesser General Public License"
logback-classic, 1.1.2, "Eclipse Public License - v 1.0, GNU Lesser General Public License"
```

Dependency_decisions.yml file has an entry for EPL:
```javascript
- - :whitelist
  - Eclipse Public License - v 1.0, GNU Lesser General Public License
  - :who: 
    :why: 
    :when: 2015-07-29 19:57:14.429395000 Z
```

**Comment by mainej** [comment]
I suspect license_finder is telling you the package has two licenses, EPL and LGPL.  So, you should run `whitelist add` twice:
```
   license_finder whitelist add "Eclipse Public License - v 1.0"
   license_finder whitelist add "GNU Lesser General Public License"
```

**Comment by nkoterba** [comment]
@mainej  Ugh! I'm an idiot...haha.

Thanks, I didn't realize that the `,` was a separator.  We just added:

`license_finder whitelist add "Eclipse Public License - v 1.0"`

and it correctly "whitelists" any libraries/dependencies that use that dependency.

Thanks for the eye-opener! =)
