### ISSUE TITLE
Suggestion to increment Version to RC or SNAPSHOT for current GitHub Source

### ISSUE THREAD

**Issue by nkoterba** [pivotal/LicenseFinder#165]
I'm now using the Github source for license_builder on my system due to fixes and features that are not currently available in 2.0.4 and via RubyGems.

This is how I did it (for others who are interested): 
```javascript
gem install specific_install
gem specific_install -l https://github.com/pivotal/LicenseFinder.git
```

However, when I check the version using:
```javascript
nk-mbp:Code a$ license_finder version
2.0.4
```

I get version 2.0.4 which is the same version on RubyGems, however, the GitHub source is DEFINITELY updated from the RubyGems version.

I suggest updating the GitHub version to be more informative and meaninful, e.g.

`2.0.5-rc1`

or even

`2.0.5-rc`.

This will at least make it more obvious to those pulling from GitHub that they are on an RC or at least not using the same version currently available on RubyGems.

**Comment by flavorjones** [comment]
Apologies for not responding earlier. v2.1.0.rc1 was released on Nov 3.
