### ISSUE TITLE
Setup instruction seem incomplete, complains about builder-3.2.2

### ISSUE THREAD

**Issue by sschuberth** [pivotal/LicenseFinder#171]
I ran `gem install license_finder` followed by `license_finder`, which gives

    $ license_finder
    C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find builder-3.2.2 in any of the sources (Bundler::GemNotFound)
            from C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `map!'
            from C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `materialize'
            from C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
            from C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/definition.rb:185:in `specs_for'
            from C:/Ruby/lib/ruby/gems/2.2.0/gems/license_finder-2.0.4/lib/license_finder/package_managers/bundler.rb:13:in `current_packages'
            from C:/Ruby/lib/ruby/gems/2.2.0/gems/license_finder-2.0.4/lib/license_finder/package_manager.rb:37:in `current_packages_with_relations'
            from C:/Ruby/lib/ruby/gems/2.2.0/gems/license_finder-2.0.4/lib/license_finder/package_manager.rb:23:in `each'
            from C:/Ruby/lib/ruby/gems/2.2.0/gems/license_finder-2.0.4/lib/license_finder/package_manager.rb:23:in `flat_map'
            from C:/Ruby/lib/ruby/gems/2.2.0/gems/license_finder-2.0.4/lib/license_finder/package_manager.rb:23:in `current_packages'
            from C:/Ruby/lib/ruby/gems/2.2.0/gems/license_finder-2.0.4/lib/license_finder/core.rb:60:in `current_packages'
            from C:/Ruby/lib/ruby/gems/2.2.0/gems/license_finder-2.0.4/lib/license_finder/core.rb:55:in `decision_applier'
            from C:/Ruby/lib/ruby/gems/2.2.0/gems/license_finder-2.0.4/lib/license_finder/cli/main.rb:26:in `action_items'
            from C:/Ruby/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
            from C:/Ruby/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
            from C:/Ruby/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
            from C:/Ruby/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
            from C:/Ruby/lib/ruby/gems/2.2.0/gems/license_finder-2.0.4/bin/license_finder:5:in `<top (required)>'
            from C:/Ruby/bin/license_finder:23:in `load'
            from C:/Ruby/bin/license_finder:23:in `<main>'

A manual `gem install builder` solved that problem, but now I'm getting complaints about `trollop-2.0`. I guess the setup instruction are missing a `bundler install` related step?

**Comment by sschuberth** [comment]
Thanks. But thinking about it, shouldn't installing via `gem install license_finder` also install its dependencies so that it works out if the box, without the need to manually run `bundler install`?

**Comment by mainej** [comment]
You were seeing that error because **your** project depends on `builder`.  `license_finder` itself doesn't depend on `builder`.  You had to run `bundle install` to pull down your own dependencies.

To put it another way, `gem install license_finder` did install all of `license_finder`s dependencies.  It did not (and should not) install all of your project's dependencies.  You should do that on your own schedule.

It's true that you must install your dependencies before running `license_finder`.  But it's not `license_finder`s job to know how to do that, especially considering `license_finder` interacts with several package managers and each one has many ways of being invoked and many configuration options.

**Comment by sschuberth** [comment]
> You were seeing that error because your project depends on builder.

Ah, thanks for the explanation. I have a mixed Java / Ruby source tree, and I wasn't even aware of the Ruby sub-project in the tree in the first place. Thus I was confused about the required dependencies.
