### ISSUE TITLE
List example values for `ignored_groups add`

### ISSUE THREAD

**Issue by MarkyMarkMcDonald** [pivotal/LicenseFinder#175]
I had to go digging through the code to figure out what the "group" is for npm development dependencies (I tried guessing dev and development, but not devDependencies).

Is this something you'd like me to create a pull request for?

**Comment by mainej** [comment]
A pull request would be great. You can add docs to the readme or to the cli
help. Only some of the package managers support groups, but please add
documentation for as many of them as you can.

**Comment by flavorjones** [comment]
Hmm, if someone wants to do the work, I won't object, but it seems out of scope to me. I'm not convinced if it's LF's job to educate the public on how the individual package managers work.
