### ISSUE TITLE
Is there any GO support expected in the roadmap?

### ISSUE THREAD

**Issue by meirwah** [pivotal/LicenseFinder#178]

**Comment by flavorjones** [comment]
Hi @meirwah,

Thanks for asking this question. Currently `master` has experimental support for Godeps and for git-submodules, which are the two styles of "dependency management" used here at Pivotal.

What kind of package management are you using?

Would you mind giving `master` a whirl and letting us know how it works for you?

**Comment by meirwah** [comment]
Godeps should work , I will try it out , 10x!

**Comment by flavorjones** [comment]
@meirwah How did you find the godeps support in v2.1.0.rc1? Any feedback for us?

**Comment by flavorjones** [comment]
Closing this, but would love to hear how you got on.
