### ISSUE TITLE
Approvals by dependency version

### ISSUE THREAD

**Issue by ipsi** [pivotal/LicenseFinder#183]
Working on a project with a client who does not approve Open Source projects on a per-license basis, but on a project-by-project basis, so I cannot whitelist a license and cal it done. Rather, I need to individually approve each dependency. Worse, they approve on a version-by-version basis for each dependency, so just because they've approved, say, `Junit 4.12` does *not* mean that `Junit 4.13` is approved, and I'd like a way to track that as well.

Currently, license_finder does not seem to provide a way to tell me that I've moved to a newer, unapproved, version of a dependency (or an older, unapproved version :-/).

I'd imagine this working something along the lines of `license_finder --approvals add <dependency>:<version>`. If you don't specify a version, the behavior is as-is (i.e. all versions are approved). Removals would be similar, with `approvals remove <dependency>` removing that dependency and all versions, and `approvals remove <dependency>:<version>` removing that specific version of that dependency.

**Comment by flavorjones** [comment]
The PR looks good! I'm about to merge it, so I'll close this issue.
