### ISSUE TITLE
Download license files

### ISSUE THREAD

**Issue by ph4t** [pivotal/LicenseFinder#195]
Most popular open sources licenses require us to deliver the license text to the client. We need to provide the specific project's text, not just generic license text. 
Is this currently possible with license finder?

**Comment by flavorjones** [comment]
Unfortunately, license finder does not aggregate licenses in this way today. The reality of the situation is that identifying the license text is, just by itself, a hard problem. You'll note that LicenseFinder will use the "shortcut" of looking at the license declared in the package (e.g., the Gemspec in Ruby), and falls back to looking for an exact license text match.

You may want to look into using FOSSology for this purpose, as that's also open-source and does a better job of "fuzzy matching" against license texts.
