### ISSUE TITLE
`gradlew` support is broken in 2.1.0

### ISSUE THREAD

**Issue by flavorjones** [pivotal/LicenseFinder#222]
When using a gradle wrapper (i.e., `./gradlew`) on a system that does not have `gradle` installed, the "detection" phase short-circuits and does not run the `Gradle` package manager against the project.

h/t to @glyn for reporting this issue.

**Comment by glyn** [comment]
Thanks Mike. A workaround is either to install gradle or to use a symbolic link along these lines:
```
sudo ln -s <project directory>/gradlew /usr/local/bin/gradle
```

**Comment by sschuberth** [comment]
I just saw this issue after I filed my PR #232. I'll amend the commit message to link to this issue.

**Comment by sschuberth** [comment]
Thanks to the recent merges by @Manifaust this should be fixed now.

**Comment by Manifaust** [comment]
@sschuberth thank _you_ and sorry for the delay
