### ISSUE TITLE
There's no way to allow bower to run as superuser

### ISSUE THREAD

**Issue by Manifaust** [pivotal/LicenseFinder#242]
By default bower does not like to run with the superuser permission. It will spit out an error like this:

```
Since bower is a user command, there is no need to execute it with superuser permissions.\nIf you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.\n\nhttp://www.joyent.com/blog/installing-node-and-npm\nhttps://gist.github.com/isaacs/579814\n\nYou can however run a command with sudo using --allow-root option
```

As the warning suggests, you can use the `--allow-root` option. However, there's no way to specify that flag in LicenseFinder.

**Comment by kdykeman** [comment]
This issue came up in the context of running LicenseFinder in a Docker container.  Bower happily runs as root once you add the following to your Dockerfile:
```
RUN echo '{ "allow_root": true }' > /root/.bowerrc
```
