### ISSUE TITLE
Unable to find golang dependencies with short paths

### ISSUE THREAD

**Issue by Manifaust** [pivotal/LicenseFinder#243]
license_finder is unable to find `gopkg.in/yaml.v2` because license_finder skips short package paths as a heuristic for excluding standard library packages.

It would be great if license_finder is able to differentiate between these types of packages from standard lib ones.

**Comment by flavorjones** [comment]
@Manifaust are you talking about this commit? 39af52d

**Comment by flavorjones** [comment]
I'm a little confused ... specs appear to indicate we *do* include this particular package:

https://github.com/pivotal/LicenseFinder/blob/master/spec/lib/license_finder/package_managers/go_workspace_spec.rb#L60

**Comment by Manifaust** [comment]
@flavorjones Sorry I should have been more clear earlier. The project I'm looking at does not use `.envrc`, so it's not activating `go_workspace`. Instead, it's acting `go_vendor`, which has logic to exclude paths with fewer than two slashes.

https://github.com/pivotal/LicenseFinder/blob/39af52d2364be79af32440d2668a042bbd09238b/lib/license_finder/package_managers/go_vendor.rb#L61-L63

**Comment by kdykeman** [comment]
This was addressed in [commit ` 54c98b8`](https://github.com/pivotal/LicenseFinder/commit/54c98b8).  The change was to remove the logic that was ignoring dependencies that matched a name pattern, and instread remove results that match an item returned by `go list std`.
