### ISSUE TITLE
Add possibility to pass arguments to the package manager

### ISSUE THREAD

**Issue by gwleclerc** [pivotal/LicenseFinder#255]
Hi,
I currently try to use license_finder with Jenkins on a maven 3 project.

Jenkins offer the possibility to provide custom configuration files like settings.xml for maven.
So my commands are launched this way:
`mvn install -s ${SETTINGS_MVN}`

where `${SETTINGS_MVN}` is the path of the settings.xml provided by jenkins.

This command works fine but there is no way for me to pass the `-s ${SETTINGS_MVN}` on the command launched by LicenseFinder.

I tried to find a way to set the settings.xml by a property into the MVN_OPTS but the property `org.apache.maven.user-settings` is no longer supported in maven 3.

I also tried to create an alias but it does not work.
`alias mvn=mvn -s ${SETTINGS_MVN}`

**Comment by kdykeman** [comment]
PR #305 added support for using `--maven-options` which should allow you to run `license_finder report --maven-options='-s ${SETTINGS_MVN}'`
