### ISSUE TITLE
Please add `yarn` support 

### ISSUE THREAD

**Issue by flavorjones** [pivotal/LicenseFinder#262]
Yarn is an alternative package manager for node:

https://code.facebook.com/posts/1840075619545360

**Comment by flavorjones** [comment]
Tagging @keaty because she asked!

**Comment by Jamedjo** [comment]
Looks like yarn has `yarn licenses ls --json`

**Comment by kdykeman** [comment]
PR #366 adds initial support for Yarn

**Comment by md5** [comment]
I'm looking forward to using this integration. Can we expect a new release shortly or should I plan to use a SHA reference instead of a packaged gem?
