### ISSUE TITLE
no licenses reported with Gradle 2.13/3.2.1 and license_finder 2.1.2

### ISSUE THREAD

**Issue by mamachanko** [pivotal/LicenseFinder#264]
When creating a fresh Spring Boot project with http://start.spring.io/ and Gradle for building, no licenses are reported.

Here are the steps to reproduce:
 * install Ruby 2.3.3 (we're using rbenv: `rbenv local 2.3.3`)
 * install license_finder 2.1.2
 * go to http://start.spring.io/
 * choose Gradle
 * download the project
 * add the Gradle license-finder plugin to `build.gradle`:
```
plugins {
    id "com.github.hierynomus.license" version "0.13.0"
}
```
 * configure `downloadLicenses` task
```
downloadLicenses {
    dependencyConfiguration "compile"
}
``` 
* build with `./gradlew clean build`
* create a license file
```bash
touch LICENSE
```
* run license_finder
```bash
license_finder --gradle-command='./gradlew'
................
All dependencies are approved for use
```
* no licenses have been reported

If you make it a Maven project and run `license_finder`, dependencies are being reported as expected:
```bash
license_finder
..................................................
Dependencies that need approval:
accessors-smart, 1.1, "Apache 2.0"
...
spring-test, 4.3.4.RELEASE, "Apache 2.0"
```

**Comment by mamachanko** [comment]
It turns out missing an executable `gradle` on the `PATH` is the problem, even if you're using Gradle wrapper. Apparently this is supposed to be a valid workaround:
```bash
touch /bin/gradle
chmod +x /bin/gradle
```

**Comment by kdykeman** [comment]
A fix has been committed for this associated with issue #222, but it hasn't yet been rolled up into a new release of LicenseFinder.
