### ISSUE TITLE
Please add support for Glide

### ISSUE THREAD

**Issue by kdykeman** [pivotal/LicenseFinder#270]
For Glide projects, GoVendor becomes active and does detect the dependencies; however, version information is lost.

**Comment by treeder** [comment]
Should probably focus on new `dep` tool that will supersede glide: https://github.com/golang/dep

**Comment by borski** [comment]
Should probably do both. :)

**Comment by kdykeman** [comment]
Agreed, I'll add a separate feature request for `dep` support so that we can track each independently.

**Comment by kdykeman** [comment]
see PR #365
