### ISSUE TITLE
license_finder failing for maven using different license-maven-plugin

### ISSUE THREAD

**Issue by bradfordboyle** [pivotal/LicenseFinder#284]
Running `license_finder` for a Maven-based Java poject is failing with the
following error:

> [ERROR] Could not find goal 'download-licenses' in plugin com.mycila:license-maven-plugin:2.9 among available goals remove, format, check, help -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoNotFoundException

It looks like `license_finder` is invoking `mvn license:download-licenses`.
Apparently there is more than one license-maven-plugin:

- com.mycila:license-maven-plugin
- org.codehaus.mojo:license-maven-plugin

Our project is using the first plugin, which does not have a "download-license"
goal; the second plugin is the one with the "download-license" goal. We were
able to manually run

```
mvn org.codehaus.mojo:license-maven-plugin:1.12:aggregate-download-licenses
```

to fetch all the licenses.

CC @schubert

**Comment by kdykeman** [comment]
I believe [PR-285](https://github.com/pivotal/LicenseFinder/pull/285) will fix this issue.
Waiting for CI to run before merging and closing this issue.

**Comment by kdykeman** [comment]
CI ran successfully.  The PR has been merged.
