### ISSUE TITLE
LF doesn't recognize .NET projects using 'packages' directory instead of '.nuget' for dependencies

### ISSUE THREAD

**Issue by bspeck** [pivotal/LicenseFinder#290]
As a user working on the standard Visual Studio ASP.NET sample I expect License Finder to scan my dependencies listed in the `packages` folder where visual studio auto-populates them.

Currently I will see the following output:
```
.....................
All dependencies are approved for use
```

Which can be taken as a false positive.

**Comment by bspeck** [comment]
Submitted pull request #292 to address this issue

**Comment by kdykeman** [comment]
Thanks for the PR! I've merged it in.
