### ISSUE TITLE
report exit code

### ISSUE THREAD

**Issue by Alpha4** [pivotal/LicenseFinder#298]
Hello,

I recently was tasked with integrating LicenseFinder for our projects at work and automate it with the use of a Jenkins job during so I noticed that LicenseFinder returns 0 whatever the results of the tests were (not using report would return 1 if any dependencies weren't approved)

Is this the intended return value (as in LF succeeded in creating the report file maybe ?)

**Comment by mdb** [comment]
I would appreciate non-zero exit codes as well. Here is an example of a `license_finder` execution I would expect to return non-zero but which exits 0; this is a scan of `github.com/comcast/eslint-plugin-polymer-components`:

```
LicenseFinder::NPM: [32mis active[0m
/usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/package_managers/npm.rb:35:in `npm_json': Command 'npm list --json --long' failed to execute: npm ERR! peer dep missing: eslint@>=4.18.0, required by eslint-config-standard@11.0.0 (RuntimeError)
npm ERR! peer dep missing: eslint@>=3.19.0, required by eslint-plugin-standard@3.1.0
npm ERR! peer dep missing: eslint-plugin-node@>=5.2.1, required by eslint-config-standard@11.0.0
	from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/package_managers/npm.rb:7:in `current_packages'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/package_manager.rb:90:in `current_packages_with_relations'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/scanner.rb:15:in `each'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/scanner.rb:15:in `flat_map'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/scanner.rb:15:in `active_packages'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/core.rb:81:in `current_packages'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/core.rb:76:in `decision_applier'
	from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/forwardable.rb:223:in `acknowledged'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/license_aggregator.rb:47:in `block in aggregate_packages'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/license_aggregator.rb:45:in `each'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/license_aggregator.rb:45:in `flat_map'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/license_aggregator.rb:45:in `aggregate_packages'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/license_aggregator.rb:9:in `dependencies'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/cli/main.rb:136:in `report'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/bin/license_finder:5:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.5.1/bin/license_finder:23:in `load'
	from /usr/local/rvm/gems/ruby-2.5.1/bin/license_finder:23:in `<main>'
```

Thanks!

**Comment by kdykeman** [comment]
@mdb the intended behavior is for `license_finder` to have a non-zero exit code when execution fails (and also when there are action items). If a `report` runs successfully, the exit code is `0` indicating that the report was generated (even if it's empty).

I tried running license_finder on the above repo without installing any of the required node_modules and got exactly the same stack trace as above; however, when I subsequently run `echo $?`, the exit status is `1`. If I install all of the required node_modules and the report runs successfully, the exit status goes to `0`.

Can you provide some additional information to help track down what may be happening?
1. What version of `license_finder` are you using?
1. Are you running it from a shell prompt, if so which shell?
1. What if any commands/options are you passing to `license_finder`?
1. How are you checking the exit status?

**Comment by mdb** [comment]
@kdykeman Thanks for looking into this!

1. I am using [iamjarvo's json-support fork](https://github.com/iamjarvo/LicenseFinder/tree/json-support) (it is currently a bit behind `pivotal-legacy/LicenseFinder:master`, so it's possible this is implicated).
2. I am running it from within a Kubernetes batch job which uses the `licensefinder/license_finder` Docker image as its base image, but uses [iamjarvo's json-support fork](https://github.com/iamjarvo/LicenseFinder/tree/json-support) in place of the `pivotal-legacy/LicenseFinder` `license_finder` (again, admittedly, this may be implicated). 
3. I first `npm install` the NPM dependencies successfully. Then I execute `license_finder report --format json`. 
4. I check the exit code like so:

```
if [ $? -ne 0 ]; then
  # do something
  # I do not reach this code
else
  # do something else
  # I reach this code
fi
```

Thanks for your attention on this! It is certainly possible I'm overlooking something.

**Comment by kdykeman** [comment]
@mdb LicenseFinder added support for json reports in version 5.6.0. Are you able to try that, and if so, do you still see the same issue with the exit code?

**Comment by mdb** [comment]
@kdykeman Thanks for the followup! I noticed JSON support in 5.6.0 but haven't yet had a chance to return to my previous project and test it out. After some further scrutiny, however, I do believe my specific experience related to exit-code-detectability was related to an issue on my end that does not implicated `license_finder`. Apologies for not reporting that back sooner.
