### ISSUE TITLE
--recursive option

### ISSUE THREAD

**Issue by Alpha4** [pivotal/LicenseFinder#299]
Hi again,

Using the --recursive option without report doesn't seem to have any effect. 

For example I get 149 dependencies in the report but only 57 if I only use the recursive option (same as without it)

**Comment by Alpha4** [comment]
I overlooked the results in fact ... all seems ok

**Comment by Alpha4** [comment]
Ok I did some more testing, taking my time, it just so happened that I get the same result for recursive when not using it however there is a problem when using --recursive with report : every dependency comes back as "Not approved"

[testingLF.txt](https://github.com/pivotal/LicenseFinder/files/993456/testingLF.txt)

**Comment by kdykeman** [comment]
PR #448 (which was included in [release 5.0.0](https://github.com/pivotal/LicenseFinder/blob/master/CHANGELOG.md#500--2018-01-15)) should resolve this issue.

When being run with the --recursive flag, LicenseFinder was looking for the decision file(s) in the wrong place unless an absolute path was specified using `--decisions-file`.
