### ISSUE TITLE
Can't generate report for my project written in Go (with glide)

### ISSUE THREAD

**Issue by gmflau** [pivotal/LicenseFinder#302]
I was trying to run this command "license_finder  report --recursive=RECURSIVE  --format=csv --save=my_report.csv" in my github project repo.  And I got the following output from the shell:

warning: "./..." matched no packages
warning: "./..." matched no packages
warning: "./..." matched no packages
warning: "./..." matched no packages
warning: "./..." matched no packages
warning: "./..." matched no packages
warning: "./..." matched no packages

I am expecting to receive my report in csv to show all the OSS projects and dependencies.  However, the my_report.csv file has 0 bytes (empty file) in it.  My project source is written in Go and using Glide as package management.   Am I missing something here?

**Comment by kdykeman** [comment]
Unfortunately, LicenseFinder doesn't yet include support for Glide.
Issue #270 captures the request to add support for that package manager.
