### ISSUE TITLE
license_finder-3.0.1/lib/license_finder/report.rb:16:in `sort': comparison of LicenseFinder::NpmPackage with LicenseFinder::NpmPackage failed (ArgumentError)

### ISSUE THREAD

**Issue by Bogadon** [pivotal/LicenseFinder#313]
I am getting an unhandled exception when I run license_finder, below is the stack trace.

Ruby 2.4.1, license_finder 3.0.1. Full log attached. 

It shows an error for rearmed-js. I am using a fork of this, if significant. 

> license_finder --debug
> ...
> LicenseFinder::Bundler: package 'rack-mini-profiler' has dependencies:
> LicenseFinder::Bundler: - rack
> npm ERR! invalid: rearmed-js@1.0.0 /home/developer/Projects/ital-freight-manager/node_modules/rearmed-js
> Command 'npm list --json --long > /tmp/20170713-7312-r0sm63' returned an error but parsing succeeded.
> LicenseFinder::BundlerPackage: package rake: found license 'MIT' from spec
> ...
[license_finder.txt](https://github.com/pivotal/LicenseFinder/files/1144511/license_finder.txt)

> Dependencies that need approval:
> /home/developer/.rvm/gems/ruby-2.4.1/gems/license_finder-3.0.1/lib/license_finder/report.rb:16:in `sort': comparison of LicenseFinder::NpmPackage with LicenseFinder::NpmPackage failed (ArgumentError)
> 	from /home/developer/.rvm/gems/ruby-2.4.1/gems/license_finder-3.0.1/lib/license_finder/report.rb:16:in `sorted_dependencies'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/gems/license_finder-3.0.1/lib/license_finder/reports/csv_report.rb:16:in `block in to_s'
> 	from /home/developer/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/csv.rb:1183:in `generate'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/gems/license_finder-3.0.1/lib/license_finder/reports/csv_report.rb:15:in `to_s'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/gems/license_finder-3.0.1/lib/license_finder/report.rb:4:in `of'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/gems/license_finder-3.0.1/lib/license_finder/cli/main.rb:121:in `report_of'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/gems/license_finder-3.0.1/lib/license_finder/cli/main.rb:61:in `action_items'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/gems/license_finder-3.0.1/bin/license_finder:5:in `<top (required)>'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bin/license_finder:22:in `load'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bin/license_finder:22:in `<main>'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
>

**Comment by edslocomb** [comment]
I had the same error, fixed it by doing the js toolchain upgrade ritual :

```bash
brew upgrade yarn node # or apt install yarn nodejs (assuming a yarn config in your sources.d) 
npm install npm@latest -g # yes, even if you use yarn
rm -rf node_modules
yarn install
```

I should really just write a script that does all that every 20 minutes; I still can't believe how squirrelly the js ecosystem is compared to other languages.

**Comment by pivotal-jamie-klassen** [comment]
Hello @Bogadon! Without a bit more context, I am unable to reproduce your issue. Could you post the versions of node and npm on your system? Recently (a6c03101c4646c2108b6380cab54fc5a047106f0) we upgraded our Docker image to use node 8 and npm 5. Furthermore, the `NPM` and `NpmPackage` classes have been rewritten twice in the last week -- if you check out the latest from master and install that, do you still see this error? If so, it may be useful to see your project's `package.json`.

**Comment by Bogadon** [comment]
Have tried the 'toolgrade upgrade ritual' with no affect. Using node 8.20 and npm 5.3.0.

[Gemfile.lock.txt](https://github.com/pivotal/LicenseFinder/files/1161808/Gemfile.lock.txt)
[package.json.txt](https://github.com/pivotal/LicenseFinder/files/1161809/package.json.txt)

Having switched to master I get a different exception:

> developer@tarantulahawk:~/Projects/ital-freight-manager$ node -v
> v8.2.0


> developer@tarantulahawk:~/Projects/ital-freight-manager$ npm -v
> 5.3.0
> developer@tarantulahawk:~/Projects/ital-freight-manager$ license_finder
> .................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................npm ERR! invalid: rearmed-js@1.0.0 /home/developer/Projects/ital-freight-manager/node_modules/rearmed-js
> Command 'npm list --json --long' returned an error but parsing succeeded.
> /home/developer/.rvm/gems/ruby-2.4.1/bundler/gems/LicenseFinder-841586d8014d/lib/license_finder/package_managers/npm_package.rb:36:in `decircularize': undefined method `dependencies=' for nil:NilClass (NoMethodError)
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bundler/gems/LicenseFinder-841586d8014d/lib/license_finder/package_managers/npm_package.rb:36:in `map'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bundler/gems/LicenseFinder-841586d8014d/lib/license_finder/package_managers/npm_package.rb:36:in `decircularize'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bundler/gems/LicenseFinder-841586d8014d/lib/license_finder/package_managers/npm_package.rb:36:in `map'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bundler/gems/LicenseFinder-841586d8014d/lib/license_finder/package_managers/npm_package.rb:36:in `decircularize'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bundler/gems/LicenseFinder-841586d8014d/lib/license_finder/package_managers/npm_package.rb:36:in `map'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bundler/gems/LicenseFinder-841586d8014d/lib/license_finder/package_managers/npm_package.rb:36:in `decircularize'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bundler/gems/LicenseFinder-841586d8014d/lib/license_finder/package_managers/npm_package.rb:6:in `packages_from_json'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bundler/gems/LicenseFinder-841586d8014d/lib/license_finder/package_managers/npm.rb:7:in `current_packages'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bundler/gems/LicenseFinder-841586d8014d/lib/license_finder/package_manager.rb:60:in `current_packages_with_relations'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bundler/gems/LicenseFinder-841586d8014d/lib/license_finder/package_manager.rb:23:in `each'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bundler/gems/LicenseFinder-841586d8014d/lib/license_finder/package_manager.rb:23:in `flat_map'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bundler/gems/LicenseFinder-841586d8014d/lib/license_finder/package_manager.rb:23:in `current_packages'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bundler/gems/LicenseFinder-841586d8014d/lib/license_finder/core.rb:63:in `current_packages'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bundler/gems/LicenseFinder-841586d8014d/lib/license_finder/core.rb:58:in `decision_applier'
> 	from /home/developer/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:223:in `any_packages?'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bundler/gems/LicenseFinder-841586d8014d/lib/license_finder/cli/main.rb:38:in `action_items'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bundler/gems/LicenseFinder-841586d8014d/bin/license_finder:5:in `<top (required)>'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bin/license_finder:22:in `load'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bin/license_finder:22:in `<main>'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
> 	from /home/developer/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by tuttieee** [comment]
I had the same problem.

It seems the error raises at [`Array.sort`]( https://github.com/pivotal/LicenseFinder/blob/master/lib/license_finder/report.rb#L16) because `<=>` of comparisons return `nil`.
In that case, `NpmPackage.<=>` returns `nil` because `NpmPackage.name` and/or `NpmPackage.version` are `nil`.
I fixed this error by setting default value (`''`) to `NpmPackage.name` and `NpmPackage.version` at the constructor.

**Comment by ryanmattcollins** [comment]
This issue arose because `babel` had some circular dependencies. The way npm addresses circular dependencies is by changing `dependencies` to `_dependencies` in the nested instances. This was causing issues with the way we were recursively navigating the dependency tree.

**Comment by jchesterpivotal** [comment]
I am seeing this behaviour on 3.0.4 and when running against HEAD of master. 

When I checkout 3214741, I get what I assume is the "Stack too deep" problem in #327. But the changes introduced by #329 seem to have introduced a regression on this issue.
