### ISSUE TITLE
Should recognize COPYING file as a license file

### ISSUE THREAD

**Issue by ryanwalls** [pivotal/LicenseFinder#377]
When scanning github.com/BurntSushi/toml, license finder did not find the license because it was in a COPYING file.  This is apparently a standard practice (see https://github.com/BurntSushi/toml/pull/184#issuecomment-337660728).

**Comment by ryanwalls** [comment]
FYI, this library https://github.com/benbalter/licensee supports COPYING if we wanted to use that under the covers.  But realize that is a bigger change.

**Comment by kdykeman** [comment]
This should be addressed in PR #410 
LF was only looking for candidate files under a `src` directory for Glide projects
