### ISSUE TITLE
Should recognize LICENSE.txt as a license file

### ISSUE THREAD

**Issue by ryanwalls** [pivotal/LicenseFinder#378]
Scanning github.com/spf13/cobra didn't pick up the apache license from https://github.com/spf13/cobra/blob/master/LICENSE.txt.  I imagine it's because it ends in .txt.  Ideally license finder could handle this case.

**Comment by kdykeman** [comment]
@ryanwalls LicenseFinder currently takes the approach of querying package managers for the dependency tree of a project and reporting on the licenses for those dependencies. The primary use case has been, "I'm developing some code, and I want to know the licenses for the things my code depends on." It doesn't report on licenses for the base repo itself. For the dependencies the particular package managers report, it does perform some matching based on [candidate license file names](https://github.com/pivotal/LicenseFinder/blob/f509e33ad798a21c7c9c04c98a8a9851e4ba0fb0/lib/license_finder/packages/license_files.rb#L5-L6) + a wildcard that should match regardless of the extension.

Are you running LicenseFinder on something that's including cobra as a dependency, or on cobra itself? Can you tell me more about your use case?

**Comment by ryanwalls** [comment]
@kdykeman I'm running it on our project that imports cobra.  We use glide for package management.  LicenceFinder did a good job finding most, but it reported this one as "unknown."  May not be the extension.

**Comment by kdykeman** [comment]
This should be addressed in PR #410 
LF was only looking for candidate files under a `src` directory for Glide projects
