### ISSUE TITLE
Docker image needs more documentation and doesn't seem to work

### ISSUE THREAD

**Issue by ryanwalls** [pivotal/LicenseFinder#379]
Running
```
docker run -v `pwd`:/app --rm -it --workdir /app licensefinder/license_finder /LicenseFinder/bin/license_finder
```
Yields this error:
```
/usr/bin/env: ruby: No such file or directory
```

Also, ideally `license_finder` should be on the `PATH` and be set as the `ENTRYPOINT` in the Dockerfile instead of having to pull the image and look around for the binary.

**Comment by kdykeman** [comment]
@ryanwalls not too long ago, we added a `dlf` (docker license finder) script. There's a note about how to use it in the [README](https://github.com/pivotal/LicenseFinder#docker)?

The command it runs from within that script is a bit different in that it gets a proper bash shell where environment variables and such get set up.
```
docker run -v $PWD:/scan -it licensefinder/license_finder /bin/bash -lc "cd /scan && `echo $@`"
```
Can you try either `dlf` or something like the line above and let me know if it works for you?

**Comment by kdykeman** [comment]
See #426 for some recent updates/clarification in the documentation for both using the dlf script and for folks wishing to test their contributions before submitting them.
