### ISSUE TITLE
Simplified BSD doesn't seem to get automatically recognized

### ISSUE THREAD

**Issue by ryanwalls** [pivotal/LicenseFinder#380]
This dependency, github.com/nlopes/slack, was not automatically recognized.  But github https://github.com/nlopes/slack/blob/master/LICENSE automatically recognizes it.

Another example:
https://github.com/gorilla/handlers/blob/master/LICENSE

**Comment by kdykeman** [comment]
Hi @ryanwalls, there's currently not a lot of fuzziness in LicenseFinder around the template matching, which means that a single word difference can cause a miss. In the case of both of the above, the template for matching contains the line "IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE" whereas what actually appears in the license text is "IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE" - the difference being in the word "HOLDER" vs. "OWNER". Use of the word "HOLDER" seems to be the more common usage, so as a short-term fix the template will be updated.

Issue #245 tracks the idea of adding fuzziness to the match - specifically via `licensee` as you brought up in #377. The conversation around template match fuzziness will happen in #245 once a few other things are addressed. In the meantime, I'll take this issue as mostly about updating the Simplified BSD template text.

**Comment by kdykeman** [comment]
The template text for Simplified BSD was updated in #425
