### ISSUE TITLE
Golang - LF produce same GIT commit ID as version.

### ISSUE THREAD

**Issue by MaheenAlaudeen** [pivotal/LicenseFinder#386]
We are seeing that all versions of unapproved licence provides same version (i.e. **vendored-commit id**) after running **license_finder** command. 

 Here is the sample output. 
$ license_finder
....................
Dependencies that need approval:
github.com/braintree/manners, **vendored-88c6bde47fb6b94e91ba26c9ce378acff4635aa5**, MIT
github.com/fsnotify/fsnotify, **vendored-88c6bde47fb6b94e91ba26c9ce378acff4635aa5**, "New BSD"
github.com/gin-contrib/sse, **vendored-88c6bde47fb6b94e91ba26c9ce378acff4635aa5**, MIT
github.com/gin-gonic/gin, **vendored-88c6bde47fb6b94e91ba26c9ce378acff4635aa5**, MIT

As you can see that, all the dependencies have same version number (**vendored-88c6bde47fb6b94e91ba26c9ce378acff4635aa5**) . instead of giving actual version number . 

Here is the yaml file. 

package: github.com/abc/def
import:
- package: github.com/braintree/manners
  version: ~0.4.0
- package: github.com/gin-gonic/gin
  version: ~1.2.0
- package: github.com/hashicorp/go-cleanhttp
- package: github.com/olekukonko/tablewriter
- package: github.com/sirupsen/logrus
  version: ~1.0.2
- package: github.com/spf13/cobra
- package: github.com/spf13/viper
- package: golang.org/x/crypto
  subpackages:
  - ssh/terminal
testImport:
- package: github.com/onsi/ginkgo
  version: ~1.4.0
- package: github.com/onsi/gomega
  version: ~1.2.0
- package: gopkg.in/gin-gonic/gin.v1
  version: ~1.2.0

Here is a portion of the lock file.

hash: c9d176059189ff478d28d458e283303a363633bba0123696072ac5d8d2cae807
updated: 2017-07-18T16:23:41.960984285-04:00
imports:
- name: github.com/braintree/manners
  version: 0b5e6b2c2843f4c83c2a40f96980b09cf4af733c
- name: github.com/fsnotify/fsnotify
  version: f12c6236fe7b5cf6bcf30e5935d08cb079d78334
- name: github.com/gin-contrib/sse
  version: 22d885f9ecc78bf4ee5d72b937e4bbcdc58e8cae
- name: github.com/gin-gonic/gin
  version: d459835d2b077e44f7c9b453505ee29881d5d12d
  subpackages:
  - binding
  - render
- name: github.com/golang/protobuf
  version: 2402d76f3d41f928c7902a765dfc872356dd3aad
  subpackages:
  - proto
- name: github.com/hashicorp/go-cleanhttp
  version: ad28ea4487f05916463e2423a55166280e8254b5

Any thought on why it is showing same commit id as version instead of displaying actual version?

**Comment by kdykeman** [comment]
Hi @MaheenAlaudeen,

I'm not certain, but it looks like your project is using Glide. Glide support was only recently added on master (not yet released). Prior to that addition, LicenseFinder would ungracefully fallback to what was then called the "go_vendor" package manager (recently renamed to "go_15vendorexperiment" to avoid confusion with the "govendor" package manager). When license finder decides the "go_vendor" package manager is 'active', it looks at your dependencies as though you've basically copied the code into your repo, and without understanding history, it reports the version as "vendored-<current_commit_sha>".

1. I've guessed, but are you using Glide for package management or something else?
1. Are you using the latest release (which lacks support for Glide) or a build off of master?

We'll be publishing a new release with Glide support soon.

**Comment by MaheenAlaudeen** [comment]
Thank you for your reply.

Yes we are using Glide for package management. 

We are using latest release not master.

Do you support any other package management for Golang ?

**Comment by kdykeman** [comment]
@MaheenAlaudeen in 3.0.4 the [supported project types](https://github.com/pivotal/LicenseFinder/blob/v3.0.4/README.md#supported-project-types) only included "Godep", "Go Workspace", and "Go Submodules". We've since added experimental support for `gvt`, `glide`, `dep`, and `govendor`. There are a few efforts in progress that are gating the next release, but it should be coming soon.
