### ISSUE TITLE
3.1.0 lacks TOML in gemspec

### ISSUE THREAD

**Issue by ababich** [pivotal/LicenseFinder#408]
in 3.1 release you have hard dependency on TOML
but this dependency is missing in `.gemspec` - this fails virtually any attempt to use version 3.1

**Comment by mvz** [comment]
The same goes for 4.0.0.

**Comment by mvz** [comment]
Both versions are marked as pre-release in GitHub, but are still released to rubygems. Maybe they should be yanked, and/or be re-versioned with a version number that rubygems will recognize as a pre-release?

**Comment by ryanmattcollins** [comment]
Thanks for the heads up @ababich and @mvz! Both versions have been yanked from ruby-gems until we can fix the issue.

**Comment by mvz** [comment]
Thanks, @ryanmattcollins.

**Comment by kdykeman** [comment]
This should be fixed in the newly released 3.1.1 and 4.0.1 versions.
