### ISSUE TITLE
Docker instructions in contribution guidelines are not useful

### ISSUE THREAD

**Issue by mvz** [pivotal/LicenseFinder#415]
Hi,

I'm trying to create a pull request for LicenceFinder, and since it has a lot of build dependencies, I want to use the docker image. However, if I follow the instructions, it doesn't test my current branch, but some older state of the repository.

How can I use the license finder docker image to test my branch?

**Comment by xtreme-shane-lattanzio** [comment]
Updated the docs

**Comment by mvz** [comment]
I'm not sure those changes helped. The specs will still run the branch the docker image is built with.
