### ISSUE TITLE
Shell command output longer than 64K is truncated

### ISSUE THREAD

**Issue by kim-10e** [pivotal/LicenseFinder#442]
The yarn integration calls the yarn CLI and receives a JSON object via standard out. On Mac OS X, this output is truncated, resulting in JSON parser errors.

Shell command output is handled via the Cmd class which uses open3.capture3, which under the hood is based on a streaming implementation, so the root problem may be in ruby process and shell interaction regarding standard out.

Workaround: Redirect standard out to a file, then read the file contents in the yarn integration.

**Comment by ryanmattcollins** [comment]
Hi kim-10e, thanks for the issue.

We have been trying to reproduce the issue, but can't seem to get our `stdout` to truncate. Is there any information you can provide us to help us test the issue?
