### ISSUE TITLE
Mix in_umbrella: true dependencies mix deps output is parsed incorrectly

### ISSUE THREAD

**Issue by KronicDeth** [pivotal/LicenseFinder#475]
`LicenseFinder::Mix` assumes that if a package has a starting line with `* NAME`, then it will have either a `locked at` line or a `the dependency is not available` line, but this is not the case for `in_umbrella: true` dependencies, which only have the `ok` line that signals the end of the packages lines.

3 known formats are

1. Hex package that is installed

```
* mimerl 1.0.2 (Hex package) (rebar3)
  locked at 1.0.2 (mimerl) 993f9b0e
  ok
```

2. Hex package that is not installed, but is locked

```
* bunt (Hex package) (mix)
  locked at 0.2.0 (bunt) 951c6e80
  the dependency is not available, run "mix deps.get"
```

3. `in_umbrella: true` dependency, which is in a directory under `apps`

```
* explorer 0.0.1 (apps/explorer) (mix)
  ok
```

(1) and (2) have 3 lines, but (3) only has 2 lines, which causes the `select` and `each_slice` 

https://github.com/pivotal/LicenseFinder/blob/0efa65b9cbae6000d3fcbe88d6e0674e77973b42/lib/license_finder/package_managers/mix.rb#L42-L43

to [incorrectly group lines to the wrong package or wrong part of the dependency description](https://circleci.com/gh/poanetwork/poa-explorer/349)

```
Dependencies that need approval:
at, "* explorer_web 0.0.1 (apps/explorer_web) (mix)", unknown
explorer, "* phoenix_ecto 3.3.0 (Hex package) (mix)", unknown
```

**Comment by Manifaust** [comment]
@KronicDeth thanks for the PR. Can you add a test for this scenario in the [mix_spec]?(https://github.com/pivotal/LicenseFinder/blob/master/spec/lib/license_finder/package_managers/mix_spec.rb)
