### ISSUE TITLE
Support pip v10.x

### ISSUE THREAD

**Issue by ento** [pivotal/LicenseFinder#479]
## Motivation:

[pip 10.0.0 has been released](https://github.com/pypa/pip/releases/tag/10.0.0) on Apr 14, 2018.

It includes a commit that [moves `pip.req` and `pip.download` under `pip._internal`](https://github.com/pypa/pip/commit/95bcf8c5f6394298035a7332c441868f3b0169f4#diff-752be5f1d62d5705a345e294deac2353). As [LicenseFinder depends on these modules](https://github.com/pivotal/LicenseFinder/blob/v5.1.0/bin/license_finder_pip.py#L5), we cannot run LicenseFinder in an environment with pip 10 installed.

## Workaround:

I haven't really tried this, but I think it should work if you downgrade to pip 9 just before you run LicenseFinder.

## Stacktrace:

```
$ bundle exec license_finder version
5.1.0
$ bundle exec license_finder # in a directory with requirements.txt
LicenseFinder::Pip: is active
Traceback (most recent call last):
  File "/home/ento/.gem/ruby/2.3.4/gems/license_finder-5.1.0/bin/license_finder_pip.py", line 5, in <module>
    from pip.req import parse_requirements
ImportError: No module named 'pip.req'
```

**Comment by FrederikNS** [comment]
It looks like this has already been done in 286f6790dc71c97c0e93ecdfe0c6fddad75165cc
