### ISSUE TITLE
Unable to use with python project

### ISSUE THREAD

**Issue by gravis** [pivotal/LicenseFinder#503]
We have an issue with a python project (unfortunately, I can't share the `requirements.txt` file).
`pip install` is running successfully, but license_finder crashes with:

```
root@c616ea3b9557:/code# license_finder
LicenseFinder::Pip: is active
Traceback (most recent call last):
  File "/usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/bin/license_finder_pip.py", line 29, in <module>
    in pkg_resources.working_set.resolve(requirements)]
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pip._vendor.pkg_resources.DistributionNotFound: The 'flower>=0.7.3; extra == "celery"' distribution was not found and is required by airflow
Traceback (most recent call last):
        22: from /usr/local/rvm/gems/ruby-2.5.1/bin/license_finder:23:in `<main>'
        21: from /usr/local/rvm/gems/ruby-2.5.1/bin/license_finder:23:in `load'
        20: from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/bin/license_finder:5:in `<top (required)>'
        19: from /usr/local/rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        18: from /usr/local/rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        17: from /usr/local/rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        16: from /usr/local/rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        15: from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/cli/main.rb:95:in `action_items'
        14: from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/license_aggregator.rb:13:in `any_packages?'
        13: from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/license_aggregator.rb:13:in `map'
        12: from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/license_aggregator.rb:15:in `block in any_packages?'
        11: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/forwardable.rb:223:in `any_packages?'
        10: from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/core.rb:76:in `decision_applier'
         9: from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/core.rb:81:in `current_packages'
         8: from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/scanner.rb:15:in `active_packages'
         7: from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/scanner.rb:15:in `flat_map'
         6: from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/scanner.rb:15:in `each'
         5: from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/package_manager.rb:90:in `current_packages_with_relations'
         4: from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/package_managers/pip.rb:12:in `current_packages'
         3: from /usr/local/rvm/gems/ruby-2.5.1/gems/license_finder-5.3.0/lib/license_finder/package_managers/pip.rb:52:in `pip_output'
         2: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/json/common.rb:440:in `JSON'
         1: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/json/common.rb:156:in `parse'
/usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/json/common.rb:156:in `parse': 765: unexpected token at '' (JSON::ParserError)
```

I'm using the `latest`  image on https://hub.docker.com/r/licensefinder/license_finder/tags/

Any idea how to get rid of this? 
Thanks

**Comment by witten** [comment]
Have you tried pip installing your requirements.txt before running license_finder? I had the same sort of error, and I apparently fixed it by installing my requirements. I got the idea from GitLab's use of LicenseFinder for Python projects. This is their LicenseFinder Dockerfile entrypoint script:

https://gitlab.com/gitlab-org/security-products/license-management/blob/master/run.sh#L106

**Comment by witten** [comment]
Alternatively: "If you do not want to manually run an individual package manager's prepare command (ex: `bundle install`, `npm install`, etc) to ensure your project is fully prepared to be scanned, use the `--prepare` or `-p` option which will run each active package manager's prepare command for you." Haven't tried that myself, but that's direct from the docs.

**Comment by 1efty** [comment]
I was inspired from https://gitlab.com/gitlab-org/security-products/license-management/blob/master/run.sh#L106 as well.  

The issue is the licensefinder/license_finder image is based on ubuntu where python links to /usr/bin/python2.  It's also missing the python3-pip package.

What I did to solve the issue was I made another image based on licensefinder/license_finder that did some setup as part of the entrypoint and installed `python3-pip`.

```bash
if test -f requirements.txt; then
  if test ${PYTHON_VERSION:-3} = "3"; then
    ln -sf $(which python3) $(which python)
    ln -sf $(which pip3) $(which pip)
  fi
fi
```

I think this is a suitable workaround until python2 is EOL.

**Comment by Freso** [comment]
> I think this is a suitable workaround until python2 is EOL.

Even after Py2 is EOL (in a few months), `python` should continue to refer to `python2` ("for the time being"), so that workaround could stay around "forever". In general, using `python` is discouraged, unless it’s code that’s known to work under both Py2 and Py3. See https://www.python.org/dev/peps/pep-0394/

**Comment by b2m** [comment]
You can now also add the Python version via a command line parameter:


> $  license_finder help
>    ....
>     [--python-version=PYTHON_VERSION]                # Python version to invoke pip with. Valid versions: 2 or 3. Default: 2
>    ...


As the python version used for license finder defaults to Python 2 it will fail on Python 3 projects.

This was introduced with https://github.com/pivotal/LicenseFinder/pull/622
