### ISSUE TITLE
LF reporting GoVendor is both active and not installed

### ISSUE THREAD

**Issue by balasankarc** [pivotal/LicenseFinder#507]
OS: Debian Stable
LF versions: 5.4.0 and 3.1.1

I am trying to run license_finder on the repository https://github.com/prometheus/node_exporter. With version 3.1.1, LF is detecting dependencies. But with latest version, it reports contradictions - that `LicenseFinder::Govendor` is both active and not installed. See log below
```bash
$ license_finder version
5.4.0
$ license_finder        
LicenseFinder::Go15VendorExperiment: is active
LicenseFinder::Govendor: is active
LicenseFinder::Govendor: is not installed

No dependencies recognized!
```

<Uninstalled latest version and then reinstalled version 3.1.1>

```bash
$ license_finder version
3.1.1

$ license_finder        
.......................
Dependencies that need approval:
github.com/beevik/ntp, vendored-05e55bddad50d79e6e5e28c7bfa7adc524135f41, unknown
github.com/coreos/go-systemd, vendored-05e55bddad50d79e6e5e28c7bfa7adc524135f41, unknown
github.com/ema/qdisc, vendored-05e55bddad50d79e6e5e28c7bfa7adc524135f41, MIT
github.com/godbus/dbus, vendored-05e55bddad50d79e6e5e28c7bfa7adc524135f41, unknown
github.com/mattn/go-xmlrpc, vendored-05e55bddad50d79e6e5e28c7bfa7adc524135f41, MIT
github.com/mdlayher/wifi, vendored-05e55bddad50d79e6e5e28c7bfa7adc524135f41, MIT
github.com/prometheus/client_golang, vendored-05e55bddad50d79e6e5e28c7bfa7adc524135f41, "Apache 2.0"
github.com/prometheus/client_model, vendored-05e55bddad50d79e6e5e28c7bfa7adc524135f41, "Apache 2.0"
github.com/prometheus/common, vendored-05e55bddad50d79e6e5e28c7bfa7adc524135f41, "Apache 2.0"
github.com/prometheus/procfs, vendored-05e55bddad50d79e6e5e28c7bfa7adc524135f41, "Apache 2.0"
github.com/soundcloud/go-runit, vendored-05e55bddad50d79e6e5e28c7bfa7adc524135f41, MIT
golang.org/x/sys, vendored-05e55bddad50d79e6e5e28c7bfa7adc524135f41, "New BSD"
gopkg.in/alecthomas/kingpin.v2, vendored-05e55bddad50d79e6e5e28c7bfa7adc524135f41, MIT
```

The lines seems confusing/wrong to me
```
LicenseFinder::Govendor: is active
LicenseFinder::Govendor: is not installed
```

**Comment by kdykeman** [comment]
Hi @balasankarc this is a case where the wording in the log messages may be a little confusing. LicenseFinder first checks various criteria to see which package managers the project is using. In the case of `govendor`, LicenseFinder is looking for the existing of a `vendor/vendor.json` file. If it finds that file, it makes the package manager "active".

It's only after a package manager is considered active that it checks to see if the command it uses to get the list is installed and in the path.

You're seeing different behavior with 3.1.1 because it appears that in that version, it is silently falling back or including the results from the `Go15VendorExperiment` package manager.

**Comment by balasankarc** [comment]
> It's only after a package manager is considered active that it checks to see if the command it uses to get the list is installed and in the path.
> it is silently falling back or including the results from the Go15VendorExperiment package manager.

@kdykeman Two doubts

1. What does `Go15VendorExperiment` use as the command to get the list ?
2. How can I force LF to use `Go15VendorExperiment` as package manager?

**Comment by kdykeman** [comment]
1. `Go15VendorExperiment` uses [`go list -f "{{join .Deps \"\n\"}}" ./...`](https://github.com/pivotal-legacy/LicenseFinder/blob/4a2b4d27e5f332fe97e45f39750889754c7a25de/lib/license_finder/package_managers/go_15vendorexperiment.rb#L58), and then filters out the standard packages by subtracting the results of running [`go list std`](https://github.com/pivotal-legacy/LicenseFinder/blob/4a2b4d27e5f332fe97e45f39750889754c7a25de/lib/license_finder/package_managers/go_15vendorexperiment.rb#L66-L70). The main issue with `Go15VendorExperiment` is this method of vendoring doesn't maintain any information about which version you've vendored. For this method, LF just gets the commit sha for your current working directory, [prepends that with `vendored-`](https://github.com/pivotal-legacy/LicenseFinder/blob/4a2b4d27e5f332fe97e45f39750889754c7a25de/lib/license_finder/package_managers/go_15vendorexperiment.rb#L40) and uses that as the version for every package.
1. There's currently no way to override LF's decision about which Golang package manager to use. If you want to trick it into using `Go15VendorExperiment`, you could remove or rename the package management file that activates that package manager. In the case of `govendor`, you'd remove/rename `vendor/vendor.json`.
