### ISSUE TITLE
find licenses for php

### ISSUE THREAD

**Issue by kaystrobach** [pivotal/LicenseFinder#518]
### Problem to solve

* support license_management for composer based projects

### Further details

php projects normally use composer

### What does success look like, and how can we measure that?

* extract license information from composer.lock file, contains all package licenses

```
    "packages": [
        {
            "name": "doctrine/annotations",
            ...
            "license": [
                "MIT"
            ],
            ...
        },
        ...
```

### Links / references

* https://gitlab.com/gitlab-org/gitlab-ee/issues/7739#note_110779175

**Comment by kaystrobach** [comment]
@mainej can i somehow sponsor that ability to read php packages?

For a first step it would be totally ok, to extract the **name** and the **license**s from the package.

IMHO this could not be so hard to implement, as the composer.lock file contains all the needed information.

```json
{
    "_readme": [
        "This file locks the dependencies of your project to a known state",
        "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies",
        "This file is @generated automatically"
    ],
    "content-hash": "08ca52f5eb5d5be4104ee3a5db00cc54",
    "packages": [
        {
            "name": "cweagans/composer-patches",
            "version": "1.6.5",
            "license": [
                "BSD-3-Clause"
            ],
            "require": {
                "composer-plugin-api": "^1.0",
                "php": ">=5.3.0"
            },
            "require-dev": {
                "composer/composer": "~1.0",
                "phpunit/phpunit": "~4.6"
            },
            "description": "Provides a way to patch Composer packages.",
        ...
        },
...
}
```

**Comment by mainej** [comment]
Sorry @kaystrobach I can't claim to be a contributor to this project anymore. Last time I checked, it was in the capable hands of @kdykeman. You might also reach out to @xtreme-shane-lattanzio @xtreme-vikram-yadav and @xtreme-lisheng-tai who have been the core maintainers lately.

It does, indeed, look like composer.lock contains the right kind of info. I'm glad to know GitLab is using LicenseFinder. Best of luck!

**Comment by kaystrobach** [comment]
Thanl you for the explanation. I would provide a PR myself, but I never worked with ruby before 😪

**Comment by kdykeman** [comment]
@kaystrobach, PR #231 to "Add support for PHP via Composer" is out there, but has been languishing for a while. I was hoping somebody would jump in to help fix it up to align with some of the refactoring that's been done or submit a new PR. I'll start fishing around a bit more.

**Comment by kaystrobach** [comment]
Nice have you seen thr generic approach idea as well? Maybe it makes sense to define a generic license information json format, which can be provided by composer directly or via a ugin

**Comment by kdykeman** [comment]
I definitely saw the generic approach idea as well - seems to make sense. It's probably quickest path to implement something in the current framework, and look at refactoring in the the longer term.

**Comment by kaystrobach** [comment]
@kdykeman can i help you to get that done with sponsoring part of your time maybe? Would cost me too much time to finally dig into it to the full extend.

**Comment by osis** [comment]
I'll try to take a look at this over the weekend.

**Comment by kaystrobach** [comment]
@osis thank you, maybe the universal approach is the better longterm solution 👍

**Comment by knightzac19** [comment]
@osis @kdykeman I was able to take all the hard work from the past two PRs that were up for PHP support and get them working, tests and all in #589.

**Comment by osis** [comment]
Nice!
