### ISSUE TITLE
Changelog is nearly empty

### ISSUE THREAD

**Issue by mvz** [pivotal/LicenseFinder#590]
license_finder 5.8.0 is broken for one of my projects and I tried to figure out what the difference with 5.7.1 is, but it seems only a few of the changes are actually in the changelog.

Please consider making the changelog more complete.

**Comment by xtreme-shane-lattanzio** [comment]
We will try to be more active about this. We currently auto populate the changelog based on tags such as [Added] or [Fixed] being in commit messages. We will be sure to audit change logs going forward to be more detailed.
