### ISSUE TITLE
License check fails when .bundle is present but gems are not vendored

### ISSUE THREAD

**Issue by mvz** [pivotal/LicenseFinder#591]
I have a project directory where a `.bundle/` directory is present, and LicenseFinder fails with an error:

```
$ license_finder
LicenseFinder::Bundler: is active
Traceback (most recent call last):
	25: from /home/matijs/.rbenv/versions/2.6.3/bin/license_finder:23:in `<main>'
	24: from /home/matijs/.rbenv/versions/2.6.3/bin/license_finder:23:in `load'
	23: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/license_finder-5.8.0/bin/license_finder:6:in `<top (required)>'
	22: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	21: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	20: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	19: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	18: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/license_finder-5.8.0/lib/license_finder/cli/main.rb:99:in `action_items'
	17: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/license_finder-5.8.0/lib/license_finder/license_aggregator.rb:15:in `any_packages?'
	16: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/license_finder-5.8.0/lib/license_finder/license_aggregator.rb:15:in `map'
	15: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/license_finder-5.8.0/lib/license_finder/license_aggregator.rb:17:in `block in any_packages?'
	14: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:224:in `any_packages?'
	13: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/license_finder-5.8.0/lib/license_finder/core.rb:78:in `decision_applier'
	12: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/license_finder-5.8.0/lib/license_finder/core.rb:83:in `current_packages'
	11: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/license_finder-5.8.0/lib/license_finder/scanner.rb:17:in `active_packages'
	10: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/license_finder-5.8.0/lib/license_finder/scanner.rb:17:in `flat_map'
	 9: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/license_finder-5.8.0/lib/license_finder/scanner.rb:17:in `each'
	 8: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/license_finder-5.8.0/lib/license_finder/package_manager.rb:97:in `current_packages_with_relations'
	 7: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/license_finder-5.8.0/lib/license_finder/package_managers/bundler.rb:15:in `current_packages'
	 6: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/license_finder-5.8.0/lib/license_finder/package_managers/bundler.rb:47:in `details'
	 5: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/license_finder-5.8.0/lib/license_finder/package_managers/bundler.rb:62:in `gem_details'
	 4: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/definition.rb:237:in `specs_for'
	 3: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/definition.rb:170:in `specs'
	 2: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/spec_set.rb:85:in `materialize'
	 1: from /home/matijs/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/spec_set.rb:85:in `map!'
/home/matijs/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/spec_set.rb:91:in `block in materialize': Could not find rake-12.3.2 in any of the sources (Bundler::GemNotFound)
```

If I remove the following lines from `lib/license_finder/package_managers/bundler.rb`, the failure goes away.

```ruby
      if File.exist?(bundler_config_path)
        ::Bundler.reset!
        ::Bundler.configure
      end
```

To reproduce, check out https://github.com/mvz/ripper_ruby_parser, and, in the project directory, run:

```bash
bundle --with development
license_finder
```

**Comment by mvz** [comment]
Actually, the two steps I gave at the end seem to work in any project, including LicenseFinder itself.

**Comment by Unknown-Guy** [comment]
Having the same issue. Had `.bundle\config` in project dir. Removing it does not solve the issue. It is looking for gem where they are not(I have them installed globally):
```
/Users/Me/.rbenv/versions/2.6.0/lib/ruby/site_ruby/2.6.0/bundler/source/path.rb:198:in `load_spec_files': The path `/Users/Me/Projects/irec/bundler/gems/active_pdftk-a1065e8f0d21` does not exist. (Bundler::PathError)
```

```bash
[0] % bundle show active_pdftk
/Users/Me/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/active_pdftk-a1065e8f0d21
```

Rolled back to version 5.7.1 and it works fine.

**Comment by mvz** [comment]
@Unknown-Guy have you tried removing the entire `.bundle` directory?

**Comment by mvz** [comment]
@Unknown-Guy actually, your issue may be different since it looks like your active_pdftk may be a gem whose source is a git repository.

**Comment by Unknown-Guy** [comment]
Yes, removed whole `.bundle` directory but then it was still looking for gems under `/Users/Me/Projects/irec/bundler/gems/` which is incorrect. The project is an engine if that matters.

**Comment by mvz** [comment]
If removing the `.bundle` directory doesn't fix it, it is definitely a different problem and you should probably create a separate github issue.

**Comment by Unknown-Guy** [comment]
Yes, sounds like that. Even tracked down what causes it.

**Comment by DavidS** [comment]
I'm seeing the same traceback with 5.9.1: https://travis-ci.com/puppetlabs/ace/builds/115403102#L982-L1010

Funnily enough I can't reproduce that locally (where I'm using the system ruby and not RVM or rbenv).

**Comment by mvz** [comment]
@DavidS Travis sets some bundler options, which cause bundler to create a `.bundle/` directory to store those options as new defaults for that project. That may not happen locally.

**Comment by DavidS** [comment]
For some reason https://github.com/puppetlabs/ace/pull/45/files#diff-354f30a63fb0907d4ad57269548329e3R10 fixed it. :man_shrugging:

**Comment by jessebs** [comment]
I'm seeing similar behavior but a different backtrace.  I tstarted in 5.8.0 and still persists in 5.9.2.  Deleting the .bundle directory makes the issue go away but that isn't a sustainable solution for us.

`
license_finder --quiet --decisions_file licensing/approvals.yml
Traceback (most recent call last):
	27: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/bin/ruby_executable_hooks:15:in `<main>'
	26: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/bin/ruby_executable_hooks:15:in `eval'
	25: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/bin/license_finder:23:in `<main>'
	24: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/bin/license_finder:23:in `load'
	23: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/license_finder-5.9.2/bin/license_finder:6:in `<top (required)>'
	22: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	21: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	20: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	19: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	18: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/license_finder-5.9.2/lib/license_finder/cli/main.rb:100:in `action_items'
	17: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:15:in `any_packages?'
	16: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:15:in `map'
	15: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:17:in `block in any_packages?'
	14: from /var/jenkins/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/forwardable.rb:223:in `any_packages?'
	13: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/license_finder-5.9.2/lib/license_finder/core.rb:78:in `decision_applier'
	12: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/license_finder-5.9.2/lib/license_finder/core.rb:83:in `current_packages'
	11: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/license_finder-5.9.2/lib/license_finder/scanner.rb:17:in `active_packages'
	10: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/license_finder-5.9.2/lib/license_finder/scanner.rb:17:in `flat_map'
	 9: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/license_finder-5.9.2/lib/license_finder/scanner.rb:17:in `each'
	 8: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/license_finder-5.9.2/lib/license_finder/package_manager.rb:97:in `current_packages_with_relations'
	 7: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/license_finder-5.9.2/lib/license_finder/package_managers/bundler.rb:15:in `current_packages'
	 6: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/license_finder-5.9.2/lib/license_finder/package_managers/bundler.rb:47:in `details'
	 5: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/license_finder-5.9.2/lib/license_finder/package_managers/bundler.rb:62:in `gem_details'
	 4: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/bundler-2.0.2/lib/bundler/definition.rb:237:in `specs_for'
	 3: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/bundler-2.0.2/lib/bundler/definition.rb:170:in `specs'
	 2: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/bundler-2.0.2/lib/bundler/spec_set.rb:81:in `materialize'
	 1: from /var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/bundler-2.0.2/lib/bundler/spec_set.rb:81:in `map!'
/var/jenkins/.rvm/gems/ruby-2.5.1@armagh/gems/bundler-2.0.2/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find rake-12.3.3 in any of the sources (Bundler::GemNotFound)
`

**Comment by jessebs** [comment]
I just tried with 5.11.1 and was unable to reproduce the error.

**Comment by mvz** [comment]
Yes, I can confirm that this problem no longer occurs with 5.11.1. Thanks to whoever fixed it!
