### ISSUE TITLE
crash when elixir is not available

### ISSUE THREAD

**Issue by chulkilee** [pivotal/LicenseFinder#607]
#594 introduced it 😨 tested on 2a39a67207d5ae09e47e6cae366506dba6358892

When `elixir` command is not available, it raises error. I didn't know how that method is going to be called. Is there any way to skip a `PackageManager` handling? It seems like calling the package manager command from `initialize` is a bad idea.

However, `lib/license_finder/package_managers/mix.rb` does not have any code about "detecting it" 😕

**Comment by DavidS** [comment]
This now has been released with 5.10 and is breaking CI in the wild: https://travis-ci.org/puppetlabs/puppet-resource_api/jobs/577393655

**Comment by DavidS** [comment]
This has been fixed by #617 , released in 5.10.1 just a few minutes ago. Thanks a lot for your time and work, @xtreme-shane-lattanzio !

**Comment by xtreme-shane-lattanzio** [comment]
@DavidS Np! Sorry for any inconvenience!!
