### ISSUE TITLE
Failure running via GitLab CI

### ISSUE THREAD

**Issue by LimeBlast** [pivotal/LicenseFinder#610]
I'm trying to add license_finder to our gitlab pipeline, but I'm having some trouble making it work.

I've set-up the environment to be the same as the rspec job uses (so, `bundle install`, `yarn install`, etc..), but when it comes to running the `license_finder` command, it fails:

```
$ license_finder report --format html > licence_finder/report.html
/usr/local/lib/ruby/2.6.0/bundler/spec_set.rb:91:in `block in materialize': Could not find concurrent-ruby-1.1.5 in any of the sources (Bundler::GemNotFound)
	from /usr/local/lib/ruby/2.6.0/bundler/spec_set.rb:85:in `map!'
	from /usr/local/lib/ruby/2.6.0/bundler/spec_set.rb:85:in `materialize'
	from /usr/local/lib/ruby/2.6.0/bundler/definition.rb:170:in `specs'
	from /usr/local/lib/ruby/2.6.0/bundler/definition.rb:237:in `specs_for'
	from /usr/local/bundle/gems/license_finder-5.9.2/lib/license_finder/package_managers/bundler.rb:62:in `gem_details'
	from /usr/local/bundle/gems/license_finder-5.9.2/lib/license_finder/package_managers/bundler.rb:47:in `details'
	from /usr/local/bundle/gems/license_finder-5.9.2/lib/license_finder/package_managers/bundler.rb:15:in `current_packages'
	from /usr/local/bundle/gems/license_finder-5.9.2/lib/license_finder/package_manager.rb:97:in `current_packages_with_relations'
	from /usr/local/bundle/gems/license_finder-5.9.2/lib/license_finder/scanner.rb:17:in `each'
	from /usr/local/bundle/gems/license_finder-5.9.2/lib/license_finder/scanner.rb:17:in `flat_map'
	from /usr/local/bundle/gems/license_finder-5.9.2/lib/license_finder/scanner.rb:17:in `active_packages'
	from /usr/local/bundle/gems/license_finder-5.9.2/lib/license_finder/core.rb:83:in `current_packages'
	from /usr/local/bundle/gems/license_finder-5.9.2/lib/license_finder/core.rb:78:in `decision_applier'
	from /usr/local/lib/ruby/2.6.0/forwardable.rb:224:in `acknowledged'
	from /usr/local/bundle/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:51:in `block in aggregate_packages'
	from /usr/local/bundle/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:49:in `each'
	from /usr/local/bundle/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:49:in `flat_map'
	from /usr/local/bundle/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:49:in `aggregate_packages'
	from /usr/local/bundle/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:11:in `dependencies'
	from /usr/local/bundle/gems/license_finder-5.9.2/lib/license_finder/cli/main.rb:139:in `report'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /usr/local/bundle/gems/license_finder-5.9.2/bin/license_finder:6:in `<top (required)>'
	from /usr/local/bundle/bin/license_finder:23:in `load'
	from /usr/local/bundle/bin/license_finder:23:in `<main>'
```

I'm not sure if this is because I'm doing something wrong - it works fine within the development environment (which is near identical to what's running on gitlab CI) so I'm not sure what's wrong.

Thanks.

**Comment by b2m** [comment]
Some CI servers like the current GitLab CI Runners will execute scripts in docker containers in a **non**-interactive way. In this mode the `.profile` or `.bashrc` will not get executed which is discussed in detail in [this StackExchange thread](https://unix.stackexchange.com/questions/257571/why-does-bashrc-check-whether-the-current-shell-is-interactive). This results in the described behavior that packages/bundles/scripts can not get resolved.

A workaround for this problem I am currently using is to add `source ~/.profile` to the `(before_)script` part in the license finder's job definition.

**Comment by matthiasbalke** [comment]
@LimeBlast @b2m We are facing the same issues, but calling LicenseFinder like this on GitLab CI
```yaml
license-check:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker run --rm -v `pwd`:/scan licensefinder/license_finder:5.11.1 bash -c "source ~/.profile && cd /scan && license_finder"
```

**Comment by b2m** [comment]
@matthiasbalke I do not see the benefit of your approach using docker in docker for this task compared to directly using the license finder image?

```yaml
license-check:
  image: licensefinder/license_finder:5.11.1
  stage: build
  script:
    - source ~/.profile
    - $YOUR_BUILD_SYSTEM_INSTALL_CMD
    - license_finder
```

**Comment by matthiasbalke** [comment]
@b2m you're right. Thats even better! thx.

**Comment by b2m** [comment]
> Why do you use the second step `$YOUR_BUILD_SYSTEM_INSTALL_CMD`. License Finder is doing a static analysis when using Maven, right? So it don't need the build output.

In case of `mvn` yes. In case of e.g. `npm` you either use your custom install command or use the default provided by `license_finder` by adding the `--prepare` option.

**Comment by matthiasbalke** [comment]
@b2m thanks for explaining.

If I execute maven before executing license_finder, is it possible to skip the license_finder maven invocation?

**Comment by b2m** [comment]
Ok, we are going off topic here regarding the original question but let's hope this is going to help somebody =)

License finder depends on build tools like maven to get information about licenses, collect them, ...
Avoiding the integration steps is therefore not that simple.

In case of maven you can configure license finder's call to maven by passing `maven_options` to the `license_finder` command. Check the [source code of license finder's maven integration](https://github.com/pivotal/LicenseFinder/blob/master/lib/license_finder/package_managers/maven.rb
) to understand how maven is called and find out that license finder is just using the [license-maven-plugin](https://www.mojohaus.org/license-maven-plugin/) for the task. So check the options for the plugin.

The solution for your missing Nexus access might be as simple as adding a `settings.xml` with the connection details that needs to get passed via `maven_options` to the maven command invocation in license finder. Or add the `settings.xml` to the corresponding `.m2` folder in the docker container...

Going back to GitLab CI/CD: you may also retrieve the `.m2` and `target` folders as cache folders or artifacts from a previous job to avoid reexecuting some maven build phases.

I hope that gives you all the pieces to puzzle together a working solution.

**Comment by matthiasbalke** [comment]
@b2m Yeah its getting offtopic, but thanks for the detailed answer!
