### ISSUE TITLE
Add support for kotlin, build package is gradle

### ISSUE THREAD

**Issue by saran2somu** [pivotal/LicenseFinder#613]
Please add support for kotlin its mostly used in Android development. It will helpful for  mobile developers . Its build package is gradle

**Comment by xtreme-shane-lattanzio** [comment]
@saran2somu I think this was addressed in the past with https://github.com/pivotal/LicenseFinder/pull/520. Does that help for your use case?

**Comment by saran2somu** [comment]
Yes, Great. Thank You ...
