### ISSUE TITLE
Running against Rust project produces failure which cannot be whitelisted

### ISSUE THREAD

**Issue by PhilipGough** [pivotal/LicenseFinder#616]
Hi, when running the tool against a Rust project which includes [fnv](https://github.com/servo/rust-fnv) as a dependency I get the following output:

```
Dependencies that need approval:
fnv, 1.0.6, "Apache-2.0 ,  MIT"
```

Directly adding that string to the whitelist fails to fix the error.
```
license_finder version
5.9.2
```

**Comment by xtreme-shane-lattanzio** [comment]
@PhilipGough Can you provide a detailed example to reproduce this? As in what the package file looks like and the LF whitelist command you are using?
