### ISSUE TITLE
Pipfile VCS dependencies error

### ISSUE THREAD

**Issue by nikitatselousov** [pivotal/LicenseFinder#672]
Since version 6.0.0 LicenseFinder supports Pipfile.lock for python dependencies. 
However when there are VCS packages that are specified like that in pyenv:

Pipfile:
 `
requests = {git="https://github.com/requests/requests.git"} 
`
Pipfile.lock:
 `
"requests": {
            "git": "https://github.com/requests/requests.git",
            "ref": "24092b11d74af0a766d9cc616622f38adb0044b9"
        }
`

LicenseFinder raises the following error:

`license_finder/package_managers/pipenv.rb:44:in canonicalize': undefined method sub' for nil:NilClass (NoMethodError)`
 
It seems to come from the fact that version is not specified for VCS packages in Pipfile.lock

**Comment by rjmackay** [comment]
Was this fixed by https://github.com/pivotal/LicenseFinder/commit/aae905bd16059503dda3c2d1532ce565f7f8b8e5 ?

**Comment by nikitatselousov** [comment]
Yes, thank you
