### ISSUE TITLE
Swift package manager support

### ISSUE THREAD

**Issue by abinrm** [pivotal/LicenseFinder#676]
It would be lovely if `licensefinder` could support Swift Package Manager.

https://github.com/apple/swift-package-manager

Dependencies are listed in a [Package.resolved](https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#resolving-versions-packageresolved-file) file in the project with URLs to github or other hosted repos.

An example of [Package.resolved](https://github.com/thoughtbot/ArgoJSONAPI/blob/master/Package.resolved) file

**Comment by michallaskowski** [comment]
Hi. Is there some progress on it? If not, would you accept an external contribution for this?
We are migrating some dependencies from Carthage to SPM, and will lose them in the generated reports without this feature.

**Comment by xtreme-shane-lattanzio** [comment]
Hi @michallaskowski ! We have not made any progress on this but would welcome external contributions!! Many of the package managers that we support is due to community members making pull requests so please feel free and we can review and merge :)

**Comment by michallaskowski** [comment]
@xtreme-shane-lattanzio Finally had some time to work on it. Please check my PR when you have time :)
