### ISSUE TITLE
Huge docker images

### ISSUE THREAD

**Issue by bluefish6** [pivotal/LicenseFinder#685]
Hi,

Thank you for your hard work in developing License Finder.

When I wanted to test newest version to see the improvements in action, I decided to use your official Docker Image. When I was browsing available tags, I was quite surprised when I saw the compressed sizes of the images:

| version | compressed size |
|---------|-----------------|
|   5.8.0 | 1.2 GB          |
|     5.9 | 1.7 GB          |
|    5.11 | 2.25 GB         |
|     6.0 | 2.39 GB         |

While I checked that the main reasons for this were:
- [Adding composer support](https://github.com/pivotal/LicenseFinder/commit/13ecaab7ee55c95ca973b74950fb10c3daea0784)
- [Adding `*.csproj` (for `dotnet`)](https://github.com/pivotal/LicenseFinder/commit/dee104517e0cf8ce769405910f46607a66017f40)
- [Updating openJDK](https://github.com/pivotal/LicenseFinder/commit/74c9aca6358c9dd9262790edbba2e42e84b58bd9)

and these are perfectly valid reasons for the target image to be bigger, I see that there could be done some optimizations.

1. remove installation archive for open jdk, as well as remove source code
from:
```
# install jdk 11
RUN curl -L -o openjdk12.tar.gz https://download.java.net/java/GA/jdk12.0.2/e482c34c86bd4bf8b56c0b35558996b9/10/GPL/openjdk-12.0.2_linux-x64_bin.tar.gz && \
    tar xvf openjdk12.tar.gz && \
    sudo mv jdk-12.0.2 /opt/
```
to:
```
# install jdk 12
RUN curl -L -o openjdk12.tar.gz https://download.java.net/java/GA/jdk12.0.2/e482c34c86bd4bf8b56c0b35558996b9/10/GPL/openjdk-12.0.2_linux-x64_bin.tar.gz && \
    tar xvf openjdk12.tar.gz && \
    rm openjdk12.tar.gz && \
    sudo mv jdk-12.0.2 /opt/ && \
    sudo rm /opt/jdk-12.0.2/lib/src.zip
```

2. remove deb package for microsoft:
From:
```
# install dotnet core
RUN wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb &&\
  sudo dpkg -i packages-microsoft-prod.deb &&\
  sudo apt-get update &&\
  sudo apt-get install -y dotnet-runtime-2.1 dotnet-sdk-2.1 dotnet-sdk-2.2 dotnet-sdk-3.0
```
(by the way, there is a mess in the `Dockerfile` considering `WORKDIR`, for example currently the above downloads to directory `/go`, because earier someone installed `go` and didn't change the `WORKDIR` back to `/`.)

To:
```
# install dotnet core
WORKDIR /tmp
RUN wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb &&\
  sudo dpkg -i packages-microsoft-prod.deb &&\
  rm packages-microsoft-prod.deb &&\
  sudo apt-get update &&\
  sudo apt-get install -y dotnet-runtime-2.1 dotnet-sdk-2.1 dotnet-sdk-2.2 dotnet-sdk-3.0
```

3. Do not collect cache for pip
From
```
# install and update python-pip
RUN apt-get install -y python-pip python3-pip && \
    pip2 install --upgrade pip==$PIP_INSTALL_VERSION  && \
    pip3 install --upgrade pip==$PIP3_INSTALL_VERSION
```
To:
```
# install and update python-pip
RUN apt-get install -y python-pip python3-pip && \
    pip2 install --no-cache --upgrade pip==$PIP_INSTALL_VERSION  && \
    pip3 install --no-cache --upgrade pip==$PIP3_INSTALL_VERSION
```

And from:
```
# install conan
RUN apt-get install -y python-dev && \
	pip install --ignore-installed six --ignore-installed colorama --ignore-installed requests --ignore-installed chardet --ignore-installed urllib3 --upgrade setuptools && \
    pip install -Iv conan==1.11.2
```
To:
```
# install conan
RUN apt-get install -y python-dev && \
	pip install --no-cache --ignore-installed six --ignore-installed colorama --ignore-installed requests --ignore-installed chardet --ignore-installed urllib3 --upgrade setuptools && \
    pip install --no-cache -Iv conan==1.11.2
```

4. Clean go cache? It seems that maybe [`go clean -cache`](https://golang.org/pkg/cmd/go/internal/clean/) could remove `/gopath/src/github.com/*`, created with below piece of code:
```
# godep is now required for license_finder to work for project that are still managed with GoDep
ENV GOROOT=/go
ENV GOPATH=/gopath
ENV PATH=$PATH:$GOPATH/bin
RUN mkdir /gopath && \
  go get github.com/tools/godep && \
  go get github.com/FiloSottile/gvt && \
  go get github.com/Masterminds/glide && \
  go get github.com/kardianos/govendor && \
  go get github.com/golang/dep/cmd/dep && \
  go get -u github.com/rancher/trash
```
I mean replace:
```
  go get -u github.com/rancher/trash
```
with:
```
  go get -u github.com/rancher/trash && \
  go clean -cache
```
(Note: I don't know *go* at all)

5. Install rust with [`minimal` profile](https://forge.rust-lang.org/infra/channel-layout.html?highlight=profile#content-of-channel-manifests) (not include docs)
From:
```
# install Cargo
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
```
To:
```
# install Cargo
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y --profile minimal
```

6. Do not cache any gems:
From
```
RUN bash -lc "cd /LicenseFinder && bundle install -j4 && rake install"
```
To:
```
RUN bash -lc "cd /LicenseFinder && bundle install --no-cache --clean -j4 && rake install"
```
7. ~~Do not [install documentation](https://guides.rubygems.org/command-reference/#gem-install) for bundler, [remove cache](https://guides.rubygems.org/command-reference/#gem-sources) after installation~~ (it didn't work for me, I got `invalid option: -​-no-document` and `invalid option: -​-clear-all`)
```
# install bundler
RUN bash -lc "gem update --system && gem install bundler"
```
To:
```
# install bundler
RUN bash -lc "gem update --system && gem install bundler -​-no-document && gem sources -​-clear-all"
```

Possibly some more optimizations are possible, but the above seem like a quick win already.

**Comment by xtreme-shane-lattanzio** [comment]
Hey @bluefish6 ! Thanks for looking into this. If you would like to make your suggested optimizations and push a PR, we would be happy to see if ours tests are still good to go and then merge.

**Comment by bluefish6** [comment]
Sure, I submitted a PR, link above.
