### ISSUE TITLE
[HELP] Error saying git source not check out

### ISSUE THREAD

**Issue by djberg96** [pivotal/LicenseFinder#694]
* ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux]
* license_finder 6.1.2

I'm trying to run `license_finder` on our project at https://github.com/ManageIQ/manageiq (Gemfile at https://github.com/ManageIQ/manageiq/blob/master/Gemfile). However, I'm getting this error:

```
1: from /home/dberger/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/source/git/git_proxy.rb:198:in `find_local_revision'
/home/dberger/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/source/git/git_proxy.rb:241:in `allowed_in_path': The git source https://github.com/ManageIQ/manageiq-gems-pending.git is not yet checked out. Please run `bundle install` before trying to start your application (Bundler::GitError)
```
Except, I *have* done a `gem install`. What am I doing wrong?

Also note that I tried applying https://github.com/pivotal/LicenseFinder/pull/620, but got the same result.

**Comment by xtreme-debbie-chen** [comment]
This looks like a duplicate of https://github.com/pivotal/LicenseFinder/issues/615

Feel free to take a look and submit a PR if you can come up with a fix. If not, it's in our backlog and we'll take a look at some point in the future.

**Comment by djberg96** [comment]
@xtreme-debbie-chen Ok thanks, I'll close this one then.
