### ISSUE TITLE
Pip 20.1 internal API change

### ISSUE THREAD

**Issue by dmcauslan** [pivotal/LicenseFinder#714]
Good morning,

I caught this error today: 
```
pip3 install: LicenseFinder command 'python3 /var/lib/gems/2.5.0/gems/license_finder-6.1.2/bin/license_finder_pip.py /app/requirements.txt' failed:
	Traceback (most recent call last):
  File "/var/lib/gems/2.5.0/gems/license_finder-6.1.2/bin/license_finder_pip.py", line 26, in <module>
    if req.req == None or (req.markers != None and not req.markers.evaluate()): continue
AttributeError: 'ParsedRequirement' object has no attribute 'req'
```

It looks like pip 20.1 changed the internal api for `parse_requirements` to return a list of `ParsedRequirement` rather than `InstallRequirement`.  The new object has a `requirement` field while the old object had a `req` field.  The short term fix is pinning pip to < 20.1, but this will need a fix:

https://github.com/pivotal/LicenseFinder/blob/2f79904a8e3fcd02922638dbcb3258960523d7d9/bin/license_finder_pip.py#L25

**Comment by agconti** [comment]
Here are steps I needed to work around this issue:

Create and activate a virtualenv. Downgrade the version of pip within that env:
```
pip install pip==20.0.2  
```

Install dependencies:
```
pip3 install -r requirements.txt
```

Run license finder:
```
license_finder report --python-version=3
```

**Comment by olliemath** [comment]
Hello, any progress on this? Pip 20.0.2 is quite old now.

It should be noted that the above work-around won't work for any installs that require the newer features of pip. I'm happy to open a PR with the required change if you need somebody to fix the offending line in `license_finder_pip.py`

**Comment by xtreme-shane-lattanzio** [comment]
Hi @olliemath ! We would appreciate a PR! We have no spent the time to make the backwards compatibility which is why we recommend the downgrade for now but if you can make the change, we would be more than happy to take a look and merge it in. Thanks!!!

**Comment by olliemath** [comment]
OK, see attached PR

**Comment by olliemath** [comment]
Hello, did anyone have a chance to look at my PR? It's been open for a month.
