### ISSUE TITLE
LicenseFinder does not report Groups for Maven package manager

### ISSUE THREAD

**Issue by rvsoni** [pivotal/LicenseFinder#715]
LicenseFinder does not report Groups for Maven package manager

I run License finder too on https://github.com/apache/commons-lang and it does not report group information with provided columns arguments.

--columns=package_manager groups name version licenses license_links

[ravi.soni@GB8TRF2 commons-lang] $ license_finder report --format csv --columns=package_manager groups name version licenses license_links
LicenseFinder::Maven: is active
Maven,"",apiguardian-api,1.1.0,Apache 2.0,http://www.apache.org/licenses/LICENSE-2.0.txt
Maven,"",commons-math3,3.2,Apache 2.0,http://www.apache.org/licenses/LICENSE-2.0.txt
Maven,"",easymock,4.2,Apache 2.0,http://www.apache.org/licenses/LICENSE-2.0.txt
Maven,"",hamcrest,2.2,BSD License 3,""
Maven,"",jmh-core,1.21,"GNU General Public License (GPL), version 2, with the Classpath exception",""
Maven,"",jmh-generator-annprocess,1.21,"GNU General Public License (GPL), version 2, with the Classpath exception",""
Maven,"",jopt-simple,4.6,MIT,http://opensource.org/licenses/mit-license
Maven,"",junit-jupiter,5.6.1,Eclipse Public License v2.0,""
Maven,"",junit-jupiter-api,5.6.1,Eclipse Public License v2.0,""
Maven,"",junit-jupiter-engine,5.6.1,Eclipse Public License v2.0,""
Maven,"",junit-jupiter-params,5.6.1,Eclipse Public License v2.0,""
Maven,"",junit-pioneer,0.5.6,MIT,http://opensource.org/licenses/mit-license
Maven,"",junit-platform-commons,1.6.1,Eclipse Public License v2.0,""
Maven,"",junit-platform-engine,1.6.1,Eclipse Public License v2.0,""
Maven,"",objenesis,3.1,Apache 2.0,http://www.apache.org/licenses/LICENSE-2.0.txt
Maven,"",opentest4j,1.2.0,Apache 2.0,http://www.apache.org/licenses/LICENSE-2.0.txt

**Comment by xtreme-shane-lattanzio** [comment]
Hey @rvsoni ! I am wondering if you are looking for the `--maven_include_groups` flag. Can you try running `license_finder report --format csv --columns=package_manager groups name version licenses license_links --maven_include_groups` and let me know?

**Comment by rvsoni** [comment]
Thanks for your help, 

i dont see any changes in output after adding --maven_include_groups

[ravi.soni@GB8TRF2 commons-lang] $  license_finder report --format csv --columns=package_manager groups name version licenses license_links --maven_include_groups
LicenseFinder::Maven: is active
Maven,"",net.sf.jopt-simple:jopt-simple,4.6,MIT,http://opensource.org/licenses/mit-license
Maven,"",org.apache.commons:commons-math3,3.2,Apache 2.0,http://www.apache.org/licenses/LICENSE-2.0.txt
Maven,"",org.apiguardian:apiguardian-api,1.1.0,Apache 2.0,http://www.apache.org/licenses/LICENSE-2.0.txt
Maven,"",org.easymock:easymock,4.2,Apache 2.0,http://www.apache.org/licenses/LICENSE-2.0.txt
Maven,"",org.hamcrest:hamcrest,2.2,BSD License 3,""
Maven,"",org.junit-pioneer:junit-pioneer,0.5.6,MIT,http://opensource.org/licenses/mit-license
Maven,"",org.junit.jupiter:junit-jupiter,5.6.1,Eclipse Public License v2.0,""
Maven,"",org.junit.jupiter:junit-jupiter-api,5.6.1,Eclipse Public License v2.0,""
Maven,"",org.junit.jupiter:junit-jupiter-engine,5.6.1,Eclipse Public License v2.0,""
Maven,"",org.junit.jupiter:junit-jupiter-params,5.6.1,Eclipse Public License v2.0,""
Maven,"",org.junit.platform:junit-platform-commons,1.6.1,Eclipse Public License v2.0,""
Maven,"",org.junit.platform:junit-platform-engine,1.6.1,Eclipse Public License v2.0,""
Maven,"",org.objenesis:objenesis,3.1,Apache 2.0,http://www.apache.org/licenses/LICENSE-2.0.txt
Maven,"",org.openjdk.jmh:jmh-core,1.21,"GNU General Public License (GPL), version 2, with the Classpath exception",""
Maven,"",org.openjdk.jmh:jmh-generator-annprocess,1.21,"GNU General Public License (GPL), version 2, with the Classpath exception",""
Maven,"",org.opentest4j:opentest4j,1.2.0,Apache 2.0,http://www.apache.org/licenses/LICENSE-2.0.txt

Ravi

**Comment by rvsoni** [comment]
Pl. review Pull request https://github.com/pivotal/LicenseFinder/pull/716 for this.

it produces correct CSV output for option --columns=groups

Ravi

**Comment by xtreme-shane-lattanzio** [comment]
@rvsoni I can see the change, it is in the third column. See instead of 
`Maven,"",easymock,4.2,Apache 2.0,http://www.apache.org/licenses/LICENSE-2.0.txt`
 
you get
`Maven,"",org.easymock:easymock,4.2,Apache 2.0,http://www.apache.org/licenses/LICENSE-2.0.txt
`
Still I think it should show up in the columns as well so we will look at the PR. FYI it looks like tests do need to be updated for your change. Thanks for looking into this :)

**Comment by rvsoni** [comment]
@xtreme-shane-lattanzio  I am sorry for not updating Test cases, I m not aware of how test cases set up and execute on the ruby project.

After fixing #716 was quite simple and easy, I am getting the correct output as below 

[ravi.soni@GB8TRF2 commons-lang] $ license_finder report --format csv --columns=package_manager groups name version licenses license_links
LicenseFinder::Maven: is active
Maven,org.apiguardian,apiguardian-api,1.1.0,Apache 2.0,http://www.apache.org/licenses/LICENSE-2.0.txt
Maven,org.apache.commons,commons-math3,3.2,Apache 2.0,http://www.apache.org/licenses/LICENSE-2.0.txt
Maven,org.easymock,easymock,4.2,Apache 2.0,http://www.apache.org/licenses/LICENSE-2.0.txt
Maven,org.hamcrest,hamcrest,2.2,BSD License 3,""
Maven,org.openjdk.jmh,jmh-core,1.21,"GNU General Public License (GPL), version 2, with the Classpath exception",""
Maven,org.openjdk.jmh,jmh-generator-annprocess,1.21,"GNU General Public License (GPL), version 2, with the Classpath exception",""
Maven,net.sf.jopt-simple,jopt-simple,4.6,MIT,http://opensource.org/licenses/mit-license
Maven,org.junit.jupiter,junit-jupiter,5.6.1,Eclipse Public License v2.0,""
Maven,org.junit.jupiter,junit-jupiter-api,5.6.1,Eclipse Public License v2.0,""
Maven,org.junit.jupiter,junit-jupiter-engine,5.6.1,Eclipse Public License v2.0,""
Maven,org.junit.jupiter,junit-jupiter-params,5.6.1,Eclipse Public License v2.0,""
Maven,org.junit-pioneer,junit-pioneer,0.5.6,MIT,http://opensource.org/licenses/mit-license
Maven,org.junit.platform,junit-platform-commons,1.6.1,Eclipse Public License v2.0,""
Maven,org.junit.platform,junit-platform-engine,1.6.1,Eclipse Public License v2.0,""
Maven,org.objenesis,objenesis,3.1,Apache 2.0,http://www.apache.org/licenses/LICENSE-2.0.txt
Maven,org.opentest4j,opentest4j,1.2.0,Apache 2.0,http://www.apache.org/licenses/LICENSE-2.0.txt

Thanks for looking into it,

Ravi

**Comment by xtreme-shane-lattanzio** [comment]
@rvsoni I see your output fixes it. I am just pointing you to the `--maven_include_groups` flag to show you what it does. It affects the actual name of the dependency. This means instead of  `easymock` you get `org.easymock:easymock`. I can see this from your examples.

As for the test cases, if you run ` rake spec` in the LicenseFinder directory, you will be able to see the failure. These tests run on every PR in our concourse pipeline that is publicly viewable: https://norsk.cf-app.com/builds/621114

**Comment by rvsoni** [comment]
@xtreme-shane-lattanzio I completely get your point on using "--maven_include_groups" and it adds Group name with Artifact name as you said and it works well,

I am looking to dump CSV data into a database and want to load Group info into its own column by using --columns list so I can use group info to generate stats of dependency. by getting Group info with name as ":" separated would require special handling to get only group info and load into its own column. 

I appreciate all your help in solving this case and getting group details printer when it's defined into a list in --columns arguments

Thanks,
Ravi
