### ISSUE TITLE
Docker licensefinder/license_finder seems to use old PHP version, upgrade to 7.3 or 7.4.

### ISSUE THREAD

**Issue by Yivan** [pivotal/LicenseFinder#717]
Hello,

First, thanks a lot for this very nice tools shared with the community.

Running `docker run -t --rm licensefinder/license_finder:latest ...` was working great until Ocramius php package abandonned PHP 7.2 support.
I get this bug when trying to generate licenses for a PHP project:

```
Digest: sha256:db4b2c335af7cff297f14385ddc4dcdea87033a726c2943b941cec15ed721f94
Status: Downloaded newer image for licensefinder/license_finder:latest
Generate License Finder report...
Traceback (most recent call last):
        22: from /usr/share/rvm/gems/ruby-2.6.5/bin/license_finder:23:in `<main>'
        21: from /usr/share/rvm/gems/ruby-2.6.5/bin/license_finder:23:in `load'
        20: from /usr/share/rvm/gems/ruby-2.6.5/gems/license_finder-6.1.2/bin/license_finder:6:in `<top (required)>'
        19: from /usr/share/rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        18: from /usr/share/rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        17: from /usr/share/rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        16: from /usr/share/rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        15: from /usr/share/rvm/gems/ruby-2.6.5/gems/license_finder-6.1.2/lib/license_finder/cli/main.rb:147:in `report'
        14: from /usr/share/rvm/gems/ruby-2.6.5/gems/license_finder-6.1.2/lib/license_finder/license_aggregator.rb:11:in `dependencies'
        13: from /usr/share/rvm/gems/ruby-2.6.5/gems/license_finder-6.1.2/lib/license_finder/license_aggregator.rb:49:in `aggregate_packages'
        12: from /usr/share/rvm/gems/ruby-2.6.5/gems/license_finder-6.1.2/lib/license_finder/license_aggregator.rb:49:in `flat_map'
        11: from /usr/share/rvm/gems/ruby-2.6.5/gems/license_finder-6.1.2/lib/license_finder/license_aggregator.rb:49:in `each'
        10: from /usr/share/rvm/gems/ruby-2.6.5/gems/license_finder-6.1.2/lib/license_finder/license_aggregator.rb:51:in `block in aggregate_packages'
         9: from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/forwardable.rb:224:in `acknowledged'
         8: from /usr/share/rvm/gems/ruby-2.6.5/gems/license_finder-6.1.2/lib/license_finder/core.rb:78:in `decision_applier'
         7: from /usr/share/rvm/gems/ruby-2.6.5/gems/license_finder-6.1.2/lib/license_finder/core.rb:83:in `current_packages'
         6: from /usr/share/rvm/gems/ruby-2.6.5/gems/license_finder-6.1.2/lib/license_finder/scanner.rb:36:in `active_packages'
         5: from /usr/share/rvm/gems/ruby-2.6.5/gems/license_finder-6.1.2/lib/license_finder/scanner.rb:36:in `flat_map'
         4: from /usr/share/rvm/gems/ruby-2.6.5/gems/license_finder-6.1.2/lib/license_finder/scanner.rb:36:in `each'
         3: from /usr/share/rvm/gems/ruby-2.6.5/gems/license_finder-6.1.2/lib/license_finder/package_manager.rb:101:in `current_packages_with_relations'
         2: from /usr/share/rvm/gems/ruby-2.6.5/gems/license_finder-6.1.2/lib/license_finder/package_managers/composer.rb:14:in `current_packages'
         1: from /usr/share/rvm/gems/ruby-2.6.5/gems/license_finder-6.1.2/lib/license_finder/package_managers/composer.rb:44:in `dependency_list'
/usr/share/rvm/gems/ruby-2.6.5/gems/license_finder-6.1.2/lib/license_finder/package_managers/composer.rb:50:in `composer_json': Command 'composer licenses --format=json' failed to execute: PHP Parse error:  syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/html/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 33 (RuntimeError)
```

On Ocramius side, bug has been reported here, but it is because it does no more support PHP 7.2:
https://github.com/Ocramius/PackageVersions/issues/121

I don't know which PHP version is used by docker licensefinder/license_finder, but if it is 7.2 (pretty old and no more supported), this issue could be fixed by going to PHP 7.3 or 7.4 which will be a good thing I think.
As Ocramius is used by many open source software in conjunction with composer, it make sense to update to more recent PHP version as license finder use composer.

For now, I can no more use it : (

Feel free to ask any information needed if I can help.

Thanks for reading me.

**Comment by Yivan** [comment]
Thanks a lot for your fast fix, but there is awlays the problem : (
Could this issue be reponened please ?

I tested it but sadly last Ocramius PackageVersions works only with PHP 7.4.
Making a lint php with php 7.3 for this file bring a parse error https://github.com/Ocramius/PackageVersions/blob/master/src/PackageVersions/Installer.php#L33

Maybe it would be better to bump to php 7.4 version, so no parsing problem occurs for recent projects (and php 7.4 can parse old php file too). Here this is problem with this Ocramius package (very used by composer), but it could be happen with any project code using php 7.4 code. As all class are parsed by licensefinder, **if it encounter a php 7.4 code syntax it breaks all the license generating process** : (

There is two solutions:
- bump to php 7.4
- in case a parse error because PHP version cannot read the code, skip the file and go on processing other files so we can get the list of license. It will make it more resilient for new php syntax and prevent the all generating license process to abort.

Both solutions could be implemented in same time so it will be more robust for later.

Thanks.

**Comment by xtreme-shane-lattanzio** [comment]
@Yivan Alrighty, we will try to bump to 7.4. It make take a few days because we have an internal docker image that builds off of this and needs to be in sync but we will get it done.

**Comment by xtreme-shane-lattanzio** [comment]
@Yivan If you want to make a PR to do this bump.  I am hesitant with the skip file solution at the same time because then we could miss something in the unparsable file so maybe failing is the better way to go about this. Either way, 7.4 is modern so I am good with that part.

**Comment by Yivan** [comment]
Hi, thanks. I just made a pull request to bump to php 7.4.
I hope docker hub image will be soon available so we can activate again the license finder on our CI.

For skipping file, yes it would prevent file parsing so some license could be missed. I understand.
For now it could be leave as it, as PHP 7.4 cli will ensure no parsing error should be happen.
Maybe on day as improvement, it could be leave to user decision with a flag (something like stopOnParseError: bolean). It is just an idea.

Thanks.
