### ISSUE TITLE
CLI: dependencies remove does not remove previous manual added dependency

### ISSUE THREAD

**Issue by forelabs** [pivotal/LicenseFinder#733]
Hello guys,

while I was working with the `dependencies` I added a few with `dependencies add` command.
Later I recognized that those where part of the staging group I forgot to ignore.
After that those still apeared so I removed them with `dependencies remove`.
I thought this would remove the `add_package` entry from the decisions file, but today I recognized I now had both in file: `add_package` and `remove_package`. I think this should behave a bit more intelligent. I would expect that if I have a manually entry for this package it should remove this `add_package` from the decision file. Only if there is no entry found it should bring up a `remove_package` entry.

I do understand that the decisions.yml file is kind of a timeline, but I think this would mean for the future if one of those packages will be e.g. moved from staging group to production we would still not list it since the latest decision was `remove_package` correct?

If you don't want to change that behaviour maybe it would be good to have a better description here.
Maybe it would be good to have something like a `decisions` command.
Like `decisions list` and `decisions delete` where list would show all decisions made in the past (maybe as a nice table) and with delete you would be able to delete one entry.

I would like to discuss that, what do you think?

**Comment by xtreme-shane-lattanzio** [comment]
@forelabs I am weary of changing the current behaviour just because I am not sure about how users are using this in the wild. I am open to adding new commands that can help manipulate the decisions file to cater to your needs. That way, other users can choose whether or not to take advantage of this change.
