### ISSUE TITLE
Replace `whitelist` and `blacklist` commands with `allowlist` and `denylist

### ISSUE THREAD

**Issue by ClemMakesApps** [pivotal/LicenseFinder#745]
Since `Whitelist`/`Blacklist` have connotations about value and map to racial terms, we should replace those commands in this project with `Allowlist` and `Denylist`.

**Comment by flavorjones** [comment]
@ClemMakesApps similar work was released in v6.0.0 to replace with permitted/restricted language. See https://github.com/pivotal/LicenseFinder/pull/650 for background and https://github.com/pivotal/LicenseFinder/blob/master/CHANGELOG.md#600--2020-01-22 for the release notes.

**Comment by ClemMakesApps** [comment]
Ah. 🤦 Sorry for missing that. Thank you for the quick response!
