### ISSUE TITLE
BSD-3-Clause OR MIT Permitted but not recognized

### ISSUE THREAD

**Issue by jessebs** [pivotal/LicenseFinder#757]
We have a Yarn Dependency that gets listed as needing approval

```
Dependencies that need approval:
amdefine, 1.0.1, "BSD-3-Clause OR MIT"
```

Our approvals file permits BSD-3-Clause, MIT, and "BSD-3-Clause OR MIT", but the dependency still fails license checking

**Comment by xtreme-shane-lattanzio** [comment]
Hi @jessebs! Im not sure if this PR convo can help: https://github.com/pivotal/LicenseFinder/pull/755 but I know this feature was only partially implemented and just released with 6.6.1. Im not sure if @nicolamarella  has any context on this issue as well.

**Comment by nicolamarella** [comment]
Hi all,
seems like there is a difference between clauses that comes with parenthesis and without for some reason. For example, some are "BSD-3-Clause OR MIT", some others "(BSD-3-Clause OR MIT)". Unfortunately I did not take that into account, my bad. I will push a fix as soon as possible.

**Comment by jessebs** [comment]
Thank you

**Comment by xtreme-shane-lattanzio** [comment]
Thanks @nicolamarella !
