### ISSUE TITLE
Permitted license with AND in the name is no longer recognized as approved

### ISSUE THREAD

**Issue by rhuitl** [pivotal/LicenseFinder#770]
The license for https://mvnrepository.com/artifact/javax.activation/activation/1.1.1 is no longer recognized as permitted even though I have `Common Development and Distribution License 1.0` in the list of permitted licenses.

I found that in earlier versions of LicenseFinder, the license name was displayed in normal case. In the most recent version, it is displayed as upper case. This might have to do with the parsing of SPDX expressions that has been introduced in #755, it looks like the AND in the license name throws it off. Permitting the two licenses `COMMON DEVELOPMENT` and `DISTRIBUTION LICENSE (CDDL) Version 1.0` separately allows the check to pass.

Package: activation (Maven)

Previously:
License: Common Development and Distribution License 1.0
Result: permitted

Currently:
License: COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.0
Result: unapproved

This might be a duplicate of #765 but I am trying with the latest Docker image (reports version 6.7.0) and still have this problem.

**Comment by Pivotal-Jeff-Jun** [comment]
Hello @rhuitl,

We have attempted to fix this issue in [this branch](https://github.com/pivotal/LicenseFinder/tree/fix-issue-770) 

When you are available, feel free to check out the branch and try it out.

Let us know if it's good 😄

**Comment by rhuitl** [comment]
Hi @Pivotal-Jeff-Jun I would love to try it but I'm not familiar with Ruby and I'm struggling to run the code locally.
Neither https://github.com/pivotal/LicenseFinder/blob/master/CONTRIBUTING.md nor https://github.com/pivotal/LicenseFinder/blob/master/README.md seem to explain how to run `license_finder` from the source tree. My naive attempt failed like this:

```
> ./bin/license_finder
Traceback (most recent call last):
	2: from ./bin/license_finder:4:in `<main>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- license_finder (LoadError)
```

It's probably too obvious for someone familiar with Ruby how to run it so it's not explained anywhere 😆
