### ISSUE TITLE
adding-reports examples no longer work

### ISSUE THREAD

**Issue by timhughes** [pivotal/LicenseFinder#786]
The examples linked to from the docs no longer work.

https://github.com/pivotal/LicenseFinder/blob/master/CONTRIBUTING.md#adding-reports

- https://gist.github.com/mainej/48ac616844505d50f510
- https://gist.github.com/mainej/b190d2f138c2b9e2e20a

```
root@b2376bcc8495:/scan# ruby license_report.rb 
Traceback (most recent call last):
	2: from license_report.rb:7:in `<main>'
	1: from license_report.rb:7:in `new'
/usr/share/rvm/gems/ruby-2.7.1/gems/license_finder-6.9.0/lib/license_finder/core.rb:34:in `initialize': undefined method `logger_mode' for {:logger=>{:quiet=>true}}:Hash (NoMethodError)
```

**Comment by timhughes** [comment]
Fix is to change the initialization code to this

```ruby
lf = LicenseFinder::Core.new(LicenseFinder::Configuration.with_optional_saved_config(logger_mode: { quiet: true}))
```

**Comment by mainej** [comment]
That gist is on my personal GitHub account, but I'm no longer involved with maintaining LicenseFinder. Rather than me fixing the gist, what does the LicenseFinder team of moving it into this repo?

**Comment by timhughes** [comment]
@mainej The gists do not have any license headers so it may be best if you stick them in a PR so as not to muddy any waters.

**Comment by mainej** [comment]
@timhughes good point. Done in #791

**Comment by mainej** [comment]
@timhughes fwiw, the invocation I needed was:
```ruby
LicenseFinder::Configuration.with_optional_saved_config(logger: :quiet)
```
not
```ruby
LicenseFinder::Configuration.with_optional_saved_config(logger_mode: { quiet: true})
```
Not sure if it changed recently, but in any case, that's how you get a "quiet" logger now.
