### ISSUE TITLE
Improving performance with npm

### ISSUE THREAD

**Issue by NickWer** [pivotal/LicenseFinder#797]
Hi, is there any way we can improve the runtime for our modestly sized nodejs project? We have ~83 dependencies, and LicenseFinder takes around around 7 minutes to run, but closer to 10 when our CI runners are under load. All suggestions are welcome 🙂

**Comment by xtreme-shane-lattanzio** [comment]
Hey @NickWer ! That is pretty long. How are you actually running it? Maybe it would help to use the `--project-path` to narrow down where it is looking? It may help to just paste the part of the log for LF so we can see what exactly it is trying to do/look for so I can make a better recommendation. Let me know!

**Comment by NickWer** [comment]
I'm going to close this out since I no longer work on the project that spawned this issue. I never did find a resolution, though.
