### ISSUE TITLE
nuget lib not grabbing dependency url's

### ISSUE THREAD

**Issue by willer** [pivotal/LicenseFinder#810]
The current code is declaring nuget packages as having an unknown license all the time. I was able to resolve this pretty easily, to at least report the license URL, as the code was very close. Just replace the functions below in nuget.rb, or grab the fix to the Dir path in license_urls:

    def current_packages
      dependencies.each_with_object({}) do |dep, memo|
        path = Dir.glob("#{Dir.home}/.nuget/packages/#{dep.name.downcase}/#{dep.version}").first
        licenses = license_urls(path, dep)
        memo[dep.name] ||= NugetPackage.new(dep.name, dep.version, spec_licenses: licenses, install_path: path)
        memo[dep.name].groups << dep.assembly unless memo[dep.name].groups.include? dep.assembly
      end.values
    end

    def license_urls(path, dep)
      files = Dir["#{path}/#{dep.name}.#{dep.version}.nupkg"]
      return nil if files.empty?

      file = files.first
      Zip::File.open file do |zipfile|
        content = zipfile.read(dep.name + '.nuspec')
        Nuget.nuspec_license_urls(content)
      end
    end

**Comment by xtreme-shane-lattanzio** [comment]
Hey @willer! Thanks for looking into this. This looks good. Would it be possible for you to make a PR for this change with tests? Then we can have this merged in and released!
