### ISSUE TITLE
Empty report for Java project

### ISSUE THREAD

**Issue by Maximus905** [pivotal/LicenseFinder#829]
command `license_finder report --format=json` for [Java project](https://github.com/th2-net/th2-read-csv/tree/th2-1156) always return empty result:
```
license_finder report --format=json
LicenseFinder::Gradle: is active
{"dependencies":[]}
```
Applied plugin `"com.github.hierynomus.license" version "0.15.0"`

I don't have any ideas how to solve that. Could someone help me, please!

P.S: the same result with `--prepare` option

**Comment by xtreme-debbie-chen** [comment]
This Java project looks like it is using gradle 7, which I think means that it's running into this issue: https://github.com/pivotal/LicenseFinder/issues/821

Unfortunately, we have not found a good alternative to hierynomus license finder plugin, and we were having problems getting other similar gradle plugins to work. If you have a good understanding of gradle, we would love your input.

**Comment by xtreme-shane-lattanzio** [comment]
The new version of the plugin now supports gradle 7
