### ISSUE TITLE
Sudden extreme slowness (in CI)

### ISSUE THREAD

**Issue by mvz** [pivotal/LicenseFinder#851]
License finder just became extremely slow today when running in CI. Five hours ago, it ran in 14 seconds. Now, it takes nearly 9 minutes. There is no difference in the set of dependencies. I use the Bundler and Yarn package managers. Running locally, license finder also seems slow, but it's inconsistent and not as extreme as in CI.

**Comment by Pivotal-Jeff-Jun** [comment]
@mvz Glad to hear that it's fast again. 
I will close this issue for now, feel free to re-open it if you run into this issue again. 😄
