### ISSUE TITLE
License Finder v7.0.1 is not recognizing Yarn's `package.json`

### ISSUE THREAD

**Issue by WolfangAukang** [pivotal/LicenseFinder#894]
I'm trying to run License Finder on my project that contains Bundler, Composer and Yarn dependencies. It recognizes the Bundler and Composer dependencies successfully, but the same can't be said about Yarn.

How can I provide more info to troubleshoot this?

**Comment by WolfangAukang** [comment]
At first I thought this was related to #170, but even by not setting the project path flag, it doesn't recognize it.

**Comment by xtreme-shane-lattanzio** [comment]
Hey @WolfangAukang are you saying this worked before and the new update broke it? I think that yarn projects only trigger on finding a `yarn.lock` file. Let me know!
