### ISSUE TITLE
Documentation on `report --save` is inconsistent / misleading

### ISSUE THREAD

**Issue by moeffju** [pivotal/LicenseFinder#896]
On 7.0.1, running `license_finder help report` shows the following:

```
...
      [--format=FORMAT]                                            # Emit detailed info about what LicenseFinder is doing
                                                                   # Default: text
                                                                   # Possible values: text, html, markdown, csv, xml, json, junit
      [--write-headers], [--no-write-headers]                      # Write exported columns as header row (csv).
      [--save=SAVE]                                                # Save report to a file. Default: 'license_report.csv' in project root.
...
```

Unlike the help text suggests, the default filename is `license_report` (as the default format is `text`), so in order to get this behavior, users must pass `--save=license_report.csv --format=csv` to the call.

**Comment by xtreme-shane-lattanzio** [comment]
@moeffju I just tried this and ran `file license_report` and it is actually a CSV file. It just doesnt have a csv extension. Since the text report is just an extension of the csv report, I think this actually makes sense.

**Comment by xtreme-shane-lattanzio** [comment]
Done 09a93762dc3bd714fdcdebb4aa84af4c7dbefa04

**Comment by moeffju** [comment]
Thank you :)
