### ISSUE TITLE
License Finder returns wrong license for oj_minic_json

### ISSUE THREAD

**Issue by brunzefb** [pivotal/LicenseFinder#906]
Ran license finder on my project.  It returned:
```
oj_mimic_json, 1.0.1, "GPL-3.0, MIT"
```
If you go to the project page on github https://github.com/ohler55/oj_mimic_json, the license says  BSD-3-Clause license.

Getting even one wrong undermines trust in the program.  If it can't figure it with a great deal of certainty, the program should should mark the license as unknown.

**Comment by nertzy** [comment]
@brunzefb This is an issue with your source code. You will want to update your gemspec to accurately report the license.

See https://github.com/ohler55/oj_mimic_json/blob/a8a53ffc77a1efe7f6dfcdac34040c4a01059ad0/oj_mimic_json.gemspec#L10

**Comment by xtreme-shane-lattanzio** [comment]
Thanks for responding @nertzy ! This does seem to be the case!
