### ISSUE TITLE
Several MIT-licensed libraries are "other"

### ISSUE THREAD

**Issue by nbibler** [pivotal/LicenseFinder#92]
Using the 1.0.0.0 Ruby release, I've noticed that several libraries which have licenses defined in their gemspecs do not get their license properly recognized by license_finder.  This occurs with an empty dependencies.db (new project).  It has occurred both locally and on Travis CI.

Surprisingly, license_finder is one of the unrecognized offenders; along with minitest, addressable, json, and sqlite3.

**Comment by mainej** [comment]
Closing this with the [release of 2.0](https://groups.google.com/forum/#!topic/license-finder/rPfVHOiLI-U). If there are scenarios where `license_finder` 2.0 reports an unexpected license for individual packages, please open those as separate issues, and reference this one.
