### ISSUE TITLE
Yarn command custom configuration

### ISSUE THREAD

**Issue by radenkoletic** [pivotal/LicenseFinder#937]
Using license_finder `7.0.1`for scanning yarn project.
It would be great to add ability to provide some additional yarn options, something similar to `--maven-options`.
For example, I want to be able to add `-ignore-platform` to the yarn command and so far, I can't find the way to do it.

**Comment by xtreme-shane-lattanzio** [comment]
Hey @radenkoletic ! There actually is a `--yarn-options` flag. Have you tried it? Let me know if it works for you!

**Comment by radenkoletic** [comment]
Hey @xtreme-shane-lattanzio. Thank you for looking into this.
I can see `--yarn-options` has been added through this PR https://github.com/pivotal/LicenseFinder/pull/904. But it is not included in the `7.0.1` release. Am I right?
Will there be a new release soon? If not, is it ok to build the new docker image from the master?

**Comment by xtreme-shane-lattanzio** [comment]
@radenkoletic Whoops my bad, I didn't even realize. I am actually working on some yarn2 fixes. Once I get it done I will make a release within the next couple weeks. You can also pull the edge docker image to get the master stuff if you can't wait `docker pull licensefinder/license_finder:edge`

**Comment by radenkoletic** [comment]
That's great. Thank you, @xtreme-shane-lattanzio.
