### ISSUE TITLE
LicenseFinder dependency on bundler creates unexpected diffs

### ISSUE THREAD

**Issue by pivotalfish** [pivotal/LicenseFinder#94]
LicenseFinder itself has a dependency on Bundler, which it is then tracking as a project dependency. Because the bundler version is not specified in the gem, we get diffs with different bundler versions on different machines. Arguably bundler is a tool, not a dependency, so it should not be in the LicenseFinder gemspec.

**Comment by mainej** [comment]
Closing this with the [release of 2.0](https://groups.google.com/forum/#!topic/license-finder/rPfVHOiLI-U).  Fixing this kind of problem was a major motivation for the 2.0 work, so thanks for contributing to this discussion.
