### ISSUE TITLE
New Tag for License Finder

### ISSUE THREAD

**Issue by LeviLewis** [pivotal/LicenseFinder#957]
Hello,

We actively use LicenseFinder for out DotNet project and we're wondering when a new tag would be created so we can utilize [this update](https://github.com/pivotal/LicenseFinder/pull/903). Looks like there hasn't been a new tag since March.

If the tag is a far ways out, is there a way y'all typically recommend implementing features like these before they get tagged?

Thanks!
- Levi

**Comment by xtreme-shane-lattanzio** [comment]
Hey @LeviLewis ! I am planning to make a new release within the next week so you should be able to pull in all new fixes. I am just waiting on one PR to be merged :)

**Comment by weyert** [comment]
Yes, would be nice if we could do a new release so I can continue with my other PR for Gitlab :)

**Comment by LeviLewis** [comment]
Thanks y'all!
