### ISSUE TITLE
[BUG]  'permitted_licenses add' not working properly for all licenses using spdx-id format.  LGPL and Python for sure.

### ISSUE THREAD

**Issue by wwebster-rr** [pivotal/LicenseFinder#984]
In my workflow I have a step that contains a for loop that iterates over a list of licenses and adds them as permitted.
```
- name: 'Add Permitted Licenses'  #This is a list of Permitted Licenses, add comma separated licenses here to prevent them from 'failing' in the report
        run: |
            echo "Configuring Permitted Licenses"
            licenses="MIT,Apache-2.0,ISC,Ruby,BSD-2-Clause,BSD-3-Clause,BSD-4-Clause,WTFPL,0BSD,CC0-1.0,PSF-2.0,MPL-2.0,LGPL-2.0-only,LGPL-3.0-only,LGPL-2.1,LGPL,Python"
            for license in ${licenses//,/ }
            do
                license_finder permitted_licenses add "$license"
            done
        shell: bash
```

I can only confirm that for sure the PSF-2.0 and LGPL-3.0-only do not work properly.   These are the SPDX-id name format of the license names as found in the definitions file in this repo. LicenseFinder/lib/license_finder/license/definisions.rb

We kept getting packages 'failing' and reporting those licenses as the ones detected.  It was only after adding the 'short name' of these licenses at the end, 'LGPL' and 'Python',  did these packages detected with those licenses start passing.

I know this is not the intended behavior of the command because I use the spdx-id format of the Apache 2.0 license, Apache-2.0, in the same list and those packages pass, no problem.

For my purposes, the fix is to add the short names of these licenses as well, and it works, but wanted to point this out to you all and get it in the issues in case others are having trouble with this and come here for help.

**Comment by swarren12** [comment]
From what I can tell, the defined `spdx_id` field is currently entirely ignored when attempting to match a license.

However, _some_ licenses happen to also include the SPDX identifier in the `other_names` list. This is the case with the `Apache-2.0` example.

Changing the matching logic of `License::matches_name?` to include the `spdx_id` field should resolve this.

I've raise [a PR](https://github.com/pivotal/LicenseFinder/pull/991) for this change.
